/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import PacotePrincipal.*;

import RN.*;
import java.math.BigDecimal;
import java.math.BigInteger;
import javax.swing.JOptionPane;
/**
 *
 * @author cliente
 */
public class AtualizarVeiculo extends javax.swing.JFrame {
    private Funcionario funcionario;
    private Veiculo veiculo;
    /**
     * Creates new form AtualizarVeiculo
     */
    public AtualizarVeiculo() {
        initComponents();
    }
    public AtualizarVeiculo(Funcionario funcionario) {
        this.funcionario = funcionario;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cTFData = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        CTFKm = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CTFAno = new javax.swing.JTextField();
        CTFChassi = new javax.swing.JTextField();
        CTFModelo = new javax.swing.JTextField();
        tFPlaca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CTFCor = new javax.swing.JTextField();
        status = new javax.swing.JComboBox();
        jCCombustivel = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cTFData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTFDataActionPerformed(evt);
            }
        });
        getContentPane().add(cTFData, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 240, -1));

        jLabel19.setText("Data da compra");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        CTFKm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CTFKmActionPerformed(evt);
            }
        });
        getContentPane().add(CTFKm, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 260, 241, -1));

        jLabel8.setText("Combustível");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, -1, -1));
        getContentPane().add(CTFAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 222, 241, -1));
        getContentPane().add(CTFChassi, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 191, 241, -1));
        getContentPane().add(CTFModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 108, 241, -1));

        tFPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFPlacaActionPerformed(evt);
            }
        });
        tFPlaca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tFPlacaFocusLost(evt);
            }
        });
        getContentPane().add(tFPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 230, -1));

        jLabel5.setText("Chassi");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 194, 48, -1));

        jLabel4.setText("Placa");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel7.setText("Km");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 26));

        jLabel2.setText("Modelo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 108, 48, 21));

        jLabel6.setText("Ano");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 225, -1, -1));

        jLabel3.setText("Cor");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 147, 48, 26));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        jButton2.setText("Confirmar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, -1));

        jLabel1.setText("Status");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, -1, -1));
        getContentPane().add(CTFCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 150, 241, -1));

        status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DISPONIVEL", "INDISPONIVEL", "VENDIDO" }));
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, -1, -1));

        jCCombustivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ALCOOL", "DIESEL", "ELETRICO", "FLEX", "GAS", "GASOLINA", " ", " ", " ", " ", " " }));
        getContentPane().add(jCCombustivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cTFDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTFDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cTFDataActionPerformed

    private void CTFKmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CTFKmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CTFKmActionPerformed

    private void tFPlacaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tFPlacaFocusLost
        
        
        /*CompraRN compraRN = new CompraRN();
        Compra compra = new Compra();
        compra = compraRN.*/
    
    }//GEN-LAST:event_tFPlacaFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (this.veiculo !=null){
            VeiculoRN veiculoRN = new VeiculoRN();
            veiculo.setStatus(this.status.getSelectedItem().toString());
            if (!veiculoRN.atualizarVeiculo(this.veiculo).equals("atualizou")){
                JOptionPane.showMessageDialog(null,"Erro ao atualizar: ");
                return;
            }
        }else{
            JOptionPane.showMessageDialog(null,"Veiculo nao encontrado");
            return;
        }
        JOptionPane.showMessageDialog(null,"Atualizado com sucesso ");
        TelaInicial telaInicial = new TelaInicial(this.funcionario);
        telaInicial.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         if (JOptionPane.showConfirmDialog(null, "Tela Inicial") == 0 ){ //0 é o sim
            TelaInicial telaInicial = new TelaInicial(this.funcionario);
            telaInicial.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String placa = tFPlaca.getText();
        this.veiculo = new Veiculo();
        VeiculoRN veiculoRN = new VeiculoRN();
        veiculo = veiculoRN.buscarVeiculo(placa);
        if (veiculo == null){
            JOptionPane.showMessageDialog(null,"Veiculo nao cadastrado");
                return;
        }
        this.CTFModelo.setText(veiculo.getModelo());
        this.CTFAno.setText(Integer.toString(veiculo.getAno()));
        this.CTFChassi.setText(veiculo.getChassi());
        this.CTFCor.setText(veiculo.getCor());
        BigDecimal bd = veiculo.getKilometragem();
        this.CTFKm.setText(bd.toString());
        this.status.setSelectedItem(this.veiculo.getStatus());
        this.jCCombustivel.setSelectedItem(veiculo.getCombustivel());            
        this.CTFCor.setText(veiculo.getCor());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tFPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFPlacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtualizarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtualizarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtualizarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtualizarVeiculo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CTFAno;
    private javax.swing.JTextField CTFChassi;
    private javax.swing.JTextField CTFCor;
    private javax.swing.JTextField CTFKm;
    private javax.swing.JTextField CTFModelo;
    private javax.swing.JTextField cTFData;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jCCombustivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox status;
    private javax.swing.JTextField tFPlaca;
    // End of variables declaration//GEN-END:variables
}
