/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import PacotePrincipal.*;
import RN.*;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cliente
 */
public class BuscaTaxa extends javax.swing.JFrame {

    /**
     * Creates new form BuscaTaxa
     */
    public BuscaTaxa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tFPlacaVeiculo = new javax.swing.JTextField();
        TXBTOK = new javax.swing.JButton();
        TXBTSair = new javax.swing.JButton();
        TXBTConfirmar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTMostrarDados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Placa do veículo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 44, -1, -1));

        tFPlacaVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFPlacaVeiculoActionPerformed(evt);
            }
        });
        getContentPane().add(tFPlacaVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 41, 188, -1));

        TXBTOK.setText("OK");
        TXBTOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXBTOKActionPerformed(evt);
            }
        });
        getContentPane().add(TXBTOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 40, -1, -1));

        TXBTSair.setText("Sair");
        getContentPane().add(TXBTSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 76, 38));

        TXBTConfirmar.setText("Confirmar");
        TXBTConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXBTConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(TXBTConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, -1, 38));

        jTMostrarDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tipo", "Data Inicial", "Data Final", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTMostrarDados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tFPlacaVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFPlacaVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFPlacaVeiculoActionPerformed

    private void TXBTOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXBTOKActionPerformed
        TaxaRN taxaRN = new TaxaRN();
        List listTaxa = new ArrayList();
        String placa = this.tFPlacaVeiculo.getText();
        Veiculo veiculo = null;
        VeiculoRN veiculoRN = new VeiculoRN();
        
        veiculo = veiculoRN.buscarVeiculo(placa);
        
        
         
        if (veiculo == null){
            JOptionPane.showMessageDialog(null,"Veículo não encontrado"); 
            return ;
        }else{           
            String mostrarVeiculo = 
                    "Placa: "+veiculo.getPlaca()+"\nStatus: "+veiculo.getStatus()+
                    "\nChassi: "+veiculo.getChassi()+"\nCombustivel: "+veiculo.getCombustivel()+"\nCor: "+veiculo.getCor()+
                    "\nModelo: "+veiculo.getModelo()+"\nAno: "+veiculo.getAno()+
                    "\nKilometragem: "+veiculo.getKilometragem();
            JOptionPane.showMessageDialog(null,mostrarVeiculo);  
            
            listTaxa = taxaRN.buscarTaxa(veiculo);
            
            if (listTaxa == null){
                JOptionPane.showMessageDialog(null,"List null");
                return;
            }
            if (listTaxa.isEmpty()){
                    JOptionPane.showMessageDialog(null,"List Vazio");
                    return;
            }
            try{
                DefaultTableModel dtm = null;
                dtm = (DefaultTableModel) jTMostrarDados.getModel();
                Iterator it = listTaxa.iterator();
                
               while(it.hasNext()){
                   Taxa taxa = (Taxa) it.next();
                   dtm.addRow(new Object[]{taxa.getTipotaxa(),taxa.getDatainicialtaxa(),taxa.getDatafinaltaxa(),taxa.getValortaxa()});
               }
                //String resultado ="Tipo Taxa: "+taxa.getTipotaxa()+"\nData Inicial: "+taxa.getDatainicialtaxa()+"\nData Final: "+taxa.getDatafinaltaxa()+
                        //"\nValor Taxa: "+taxa.getValortaxa();
               // this.tFMostrarTaxa.setText(resultado);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Taxa Nao encontrada");
            }
        }
    }//GEN-LAST:event_TXBTOKActionPerformed

    private void TXBTConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXBTConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXBTConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscaTaxa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscaTaxa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscaTaxa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscaTaxa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscaTaxa().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TXBTConfirmar;
    private javax.swing.JButton TXBTOK;
    private javax.swing.JButton TXBTSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTMostrarDados;
    private javax.swing.JTextField tFPlacaVeiculo;
    // End of variables declaration//GEN-END:variables
}
