/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;
import PacotePrincipal.Promocao;
import RN.PromocaoRN;
import java.math.BigDecimal;
import java.text.ParseException;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author cliente
 */
public class CadastrarPromocao extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarPromocao
     */
    
    
    public CadastrarPromocao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inicioPromocao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        finalPromocao = new javax.swing.JTextField();
        botaoConfirmar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        percentualDesconto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        descricao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tipoPromocao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cadastro de promoções");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 14, -1, -1));

        jLabel3.setText("Data inicial");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 170, -1, -1));

        inicioPromocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioPromocaoActionPerformed(evt);
            }
        });
        getContentPane().add(inicioPromocao, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 167, 163, -1));

        jLabel4.setText("Data final");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 170, -1, -1));

        finalPromocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalPromocaoActionPerformed(evt);
            }
        });
        getContentPane().add(finalPromocao, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 167, 162, -1));

        botaoConfirmar.setText("Confirmar");
        botaoConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 297, -1, 31));

        botaoCancelar.setText("Cancelar");
        getContentPane().add(botaoCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 297, 83, 31));

        jLabel5.setText("Percentual de desconto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 213, -1, -1));
        getContentPane().add(percentualDesconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 210, 162, -1));

        jLabel6.setText("Descrição");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 248, -1, -1));
        getContentPane().add(descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 248, 331, -1));

        jLabel2.setText("Tipo de promoção");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 139, -1, -1));
        getContentPane().add(tipoPromocao, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 136, 34, -1));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(884, 34, -1, 26));

        jLabel9.setText(" tipo 1:  Km < 100    ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 84, -1, -1));

        jLabel10.setText(" tipo 2: Locação em dia da semana");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 104, -1, -1));

        jLabel11.setText("Promoção");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 64, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finalPromocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalPromocaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finalPromocaoActionPerformed

    private void inicioPromocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioPromocaoActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_inicioPromocaoActionPerformed

    private void botaoConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarActionPerformed
        Promocao promocao = new Promocao();
        promocao.setTipopromocao(Integer.parseInt(tipoPromocao.getText()));
        try{    //Formato data do VO é do tipo Date 
            Date data1 = new SimpleDateFormat("dd/MM/yyyy").parse(inicioPromocao.getText());   
            Date data2 = new SimpleDateFormat("dd/MM/yyyy").parse(finalPromocao.getText());            
            promocao.setDatainiciopromocao(data1);
            promocao.setDatafimpromocao(data2);
        }catch(ParseException erroData){
            JOptionPane.showMessageDialog(null,"Formato de data inválido");
        }
         BigDecimal bd = new BigDecimal(percentualDesconto.getText());
         promocao.setPercentualdesconto(bd);
         promocao.setDescricao(descricao.getText());
         PromocaoRN promocaoRN = new PromocaoRN();
         String mensagem = promocaoRN.cadastrarPromocao(promocao);
         JOptionPane.showMessageDialog(null,mensagem);
    }//GEN-LAST:event_botaoConfirmarActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarPromocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarPromocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarPromocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarPromocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarPromocao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoConfirmar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JTextField descricao;
    private javax.swing.JTextField finalPromocao;
    private javax.swing.JTextField inicioPromocao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField percentualDesconto;
    private javax.swing.JTextField tipoPromocao;
    // End of variables declaration//GEN-END:variables
}
