/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;


import PacotePrincipal.*;


import RN.*;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author cliente
 */
public class CadastrarCliente extends javax.swing.JFrame {
    private Funcionario funcionario=null;
    private  Veiculo veiculo=null;
    private  Aluguel aluguel=null;
    float  seguro = 0;
    private Endereco endereco=null;
    private Cliente cliente=null;
    
    /**
     * Creates new form CadastrarCliente
     */
    public CadastrarCliente() {
        initComponents();
    }

    public CadastrarCliente(Funcionario funcionario, Veiculo veiculo, Aluguel aluguel, float seguro) {
        this.funcionario= funcionario;
        this.veiculo = veiculo;
        this.aluguel = aluguel;
        this.seguro = seguro;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tFDocumento = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jCTipoPessoa = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        tFDataNascimento = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tFNome = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tFNumerodaCasa = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tFRua = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tFBairro = new javax.swing.JTextField();
        tFCidade = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tFCEP = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        tFEmail = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tFNumeroCNH = new javax.swing.JTextField();
        tFValidadeCNH = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tFPrimeiraCNH = new javax.swing.JTextField();
        tFCategoriaCNH = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        tFTelefone = new javax.swing.JTextField();
        CadTFCategoria2 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        CadBTConfirmar1 = new javax.swing.JButton();
        CadBTCancelar1 = new javax.swing.JButton();
        tFUF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tFComplemento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tFDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFDocumentoActionPerformed(evt);
            }
        });
        tFDocumento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tFDocumentoFocusLost(evt);
            }
        });
        getContentPane().add(tFDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 253, -1));

        jLabel21.setText("CPF/CNPJ");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jCTipoPessoa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FISICA", "JURIDICA" }));
        getContentPane().add(jCTipoPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabel8.setText("Tipo Pessoa");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        getContentPane().add(tFDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 240, -1));

        jLabel17.setText("Data de nascimento");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        getContentPane().add(tFNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 240, -1));

        jLabel18.setText("Nome");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));
        getContentPane().add(tFNumerodaCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 118, -1));

        jLabel19.setText("Número Casa");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, -1, -1));

        tFRua.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tFRuaFocusLost(evt);
            }
        });
        getContentPane().add(tFRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 240, -1));

        jLabel10.setText("Rua");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel14.setText("Bairro");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));
        getContentPane().add(tFBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 240, -1));
        getContentPane().add(tFCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 240, -1));

        jLabel24.setText("Cidade");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        getContentPane().add(tFCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 207, -1));

        jLabel26.setText("CEP");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));
        getContentPane().add(tFEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 240, -1));

        jLabel16.setText("Email");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel5.setText("Número CNH");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        tFNumeroCNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFNumeroCNHActionPerformed(evt);
            }
        });
        getContentPane().add(tFNumeroCNH, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 240, -1));
        getContentPane().add(tFValidadeCNH, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 438, 240, -1));

        jLabel27.setText("Validade");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 441, -1, -1));
        getContentPane().add(tFPrimeiraCNH, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 207, -1));
        getContentPane().add(tFCategoriaCNH, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 51, -1));

        jLabel29.setText("Categoria");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, -1, -1));

        jLabel30.setText("UF");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 22, -1));

        jLabel31.setText("Telefone");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));
        getContentPane().add(tFTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 207, -1));
        getContentPane().add(CadTFCategoria2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 51, -1));

        jLabel32.setText("Categoria");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, -1, -1));

        jLabel33.setText("1ª habilitação");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, -1, -1));

        CadBTConfirmar1.setText("Confirmar");
        CadBTConfirmar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadBTConfirmar1ActionPerformed(evt);
            }
        });
        getContentPane().add(CadBTConfirmar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 518, -1, 33));

        CadBTCancelar1.setText("Cancelar");
        CadBTCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadBTCancelar1ActionPerformed(evt);
            }
        });
        getContentPane().add(CadBTCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 515, -1, 39));
        getContentPane().add(tFUF, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 80, -1));

        jLabel1.setText("Complemento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));
        getContentPane().add(tFComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tFDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFDocumentoActionPerformed

    private void tFNumeroCNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFNumeroCNHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFNumeroCNHActionPerformed

    private void tFDocumentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tFDocumentoFocusLost
        this.cliente = new Cliente ();
        cliente.setCnpj(this.tFDocumento.getText());
        ClienteRN clienteRN = new ClienteRN();
        cliente = clienteRN.buscarCliente(this.tFDocumento.getText());
        
        if (cliente != null){
            this.tFNome.setText(cliente.getNome());
            this.tFDataNascimento.setText(cliente.getDatanascimento().toString());
            this.tFEmail.setText(cliente.getEmail());
            this.tFNumerodaCasa.setText(Integer.toString(cliente.getNumendereco()));
            this.tFNumeroCNH.setText(cliente.getNumcnh());
            this.tFCategoriaCNH.setText(cliente.getTipocnh());
            this.tFPrimeiraCNH.setText(cliente.getDataemissaocnh().toString());
            this.tFValidadeCNH.setText(cliente.getDatavalidadecnh().toString());
            this.tFTelefone.setText(cliente.getTelefone());
        }
            
    }//GEN-LAST:event_tFDocumentoFocusLost

    private void tFRuaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tFRuaFocusLost
        this.endereco = new Endereco();
        EnderecoRN enderecoRN = new EnderecoRN();
        this.endereco = enderecoRN.buscarEndereco(this.tFCidade.getText().toUpperCase(), this.tFRua.getText().toUpperCase());
        
        if (this.endereco != null){
                tFBairro.setText(endereco.getBairro());
                tFCidade.setText(endereco.getCidade());
                tFRua.setText(endereco.getRua().toUpperCase());
                tFUF.setText(endereco.getUf());
                tFComplemento.setText(endereco.getComplemento());
                tFCEP.setText(endereco.getCep());  
        }
            
        
    }//GEN-LAST:event_tFRuaFocusLost

    private void CadBTConfirmar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadBTConfirmar1ActionPerformed
        String mensagem=null;
        if (this.endereco == null){
            this.endereco = new Endereco();
                endereco.setBairro(tFBairro.getText());
                endereco.setCidade(tFCidade.getText());
                endereco.setRua(tFRua.getText());
                endereco.setUf(tFUF.getText());
                endereco.setComplemento(tFComplemento.getText());
                endereco.setCep(tFCEP.getText());
                
                //salvar endereco
                EnderecoRN enderecoRN = new EnderecoRN();
                mensagem = enderecoRN.atualizarEndereco(this.endereco);
                if (!mensagem.equals("CADASTROU")){
                    JOptionPane.showMessageDialog(null,"Erro ao salvar endereco: "+mensagem);
                    return;
                }
                //busca endereco pra pegar FK
                this.endereco= enderecoRN.buscarEndereco(endereco.getCidade(),endereco.getRua());
        }
        
        if (this.cliente == null){
            Cliente cliente = new Cliente();
            
            cliente.setEndereco(this.endereco);         
            cliente.setNome(this.tFNome.getText());
            Date dataNascimento=null, dataEmissaoCNH=null, dataValidadeCNH=null;
            try{    //Formato data do VO é do tipo Date 
               dataNascimento = new SimpleDateFormat("dd/MM/yyyy").parse(tFDataNascimento.getText()); 
               dataEmissaoCNH = new SimpleDateFormat("dd/MM/yyyy").parse(tFPrimeiraCNH.getText());
               dataValidadeCNH= new SimpleDateFormat("dd/MM/yyyy").parse(tFValidadeCNH.getText());;
            }catch(Exception erro){
                JOptionPane.showMessageDialog(null,"Erro na data: "+erro.getMessage());
                return;
            }
            cliente.setDatanascimento(dataNascimento);
            cliente.setEmail(this.tFEmail.getText());
            cliente.setNumendereco(Integer.parseInt(this.tFNumerodaCasa.getText()));
            cliente.setNumcnh(this.tFNumeroCNH.getText());
            cliente.setTipocnh(this.tFCategoriaCNH.getText());
            cliente.setDataemissaocnh(dataEmissaoCNH);
            cliente.setDatavalidadecnh(dataValidadeCNH);
            cliente.setTelefone(this.tFTelefone.getText());
            cliente.setTelefone(tFTelefone.getText());
            ClienteRN clienteRN = new ClienteRN();
            
            mensagem = clienteRN.cadastrarCliente(cliente, this.tFDocumento.getText());
            
            if (!mensagem.equals("CADASTROU")){
                JOptionPane.showMessageDialog(null,"Erro ao salvar Cliente: "+mensagem);
                return;
            }
            cliente= clienteRN.buscarCliente(this.tFDocumento.getText());//busca o ID de cliente
            if (cliente ==null){
                JOptionPane.showMessageDialog(null,"Erro ao pegar a PK de Cliente: "+mensagem);
                return;
            } 
        }
        aluguel.setCliente(cliente);
        aluguel.setFuncionario(this.funcionario);
        aluguel.setVeiculo(this.veiculo);
        AluguelRN aluguelRN = new AluguelRN();
        mensagem = aluguelRN.cadastrarAluguel(this.aluguel);
        
        if (!mensagem.equals("OK")){
            JOptionPane.showMessageDialog(null,"Erro ao Salvar aluguel: "+mensagem);
                return;
        }
        VeiculoRN veiculoRN = new VeiculoRN();
        mensagem = veiculoRN.atualizarVeiculo(this.veiculo);
        if (!mensagem.equals("atualizou")){
            JOptionPane.showMessageDialog(null,"Erro ao Salvar veiculo: "+mensagem);
            return;
        }
            
        //INSERIR SEGURO EM TAXA AQUI (TESTAR PRA VER SE É SIM)
        TaxaRN taxaRN = new TaxaRN();
        Taxa taxa = new Taxa();
        if (seguro!=0){
            BigDecimal taxaSeguro= new BigDecimal(seguro);
            taxa.setDatainicialtaxa(aluguel.getDataaluguel());
            taxa.setDatafinaltaxa(aluguel.getDataaluguel());
            taxa.setTipotaxa("SEGURO");
            taxa.setValortaxa(taxaSeguro);
            
            mensagem = taxaRN.cadastrarTaxa(taxa);
            if (!mensagem.equals("Taxa cadastrada com sucesso")){
                JOptionPane.showMessageDialog(null,"Erro ao Salvar taxa de seguro: "+mensagem);
                return;
            }
            
            
            
            
            ///taxa = taxaRN.buscarTaxa(taxa);
        }
        
        JOptionPane.showMessageDialog(null,"Dados salvos com sucesso");
        TelaInicial telaInicial = new TelaInicial(this.funcionario);
        telaInicial.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CadBTConfirmar1ActionPerformed

    private void CadBTCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadBTCancelar1ActionPerformed
        TelaInicial telaInicial = new TelaInicial();
        telaInicial.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CadBTCancelar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadBTCancelar1;
    private javax.swing.JButton CadBTConfirmar1;
    private javax.swing.JTextField CadTFCategoria2;
    private javax.swing.JComboBox jCTipoPessoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField tFBairro;
    private javax.swing.JTextField tFCEP;
    private javax.swing.JTextField tFCategoriaCNH;
    private javax.swing.JTextField tFCidade;
    private javax.swing.JTextField tFComplemento;
    private javax.swing.JTextField tFDataNascimento;
    private javax.swing.JTextField tFDocumento;
    private javax.swing.JTextField tFEmail;
    private javax.swing.JTextField tFNome;
    private javax.swing.JTextField tFNumeroCNH;
    private javax.swing.JTextField tFNumerodaCasa;
    private javax.swing.JTextField tFPrimeiraCNH;
    private javax.swing.JTextField tFRua;
    private javax.swing.JTextField tFTelefone;
    private javax.swing.JTextField tFUF;
    private javax.swing.JTextField tFValidadeCNH;
    // End of variables declaration//GEN-END:variables
}
