/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;


import PacotePrincipal.*;




import RN.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author a1257072
 */
public class CadastrarFornecedor extends javax.swing.JFrame {
    private Funcionario funcionario = null;
    private Veiculo veiculo=null;
    private Compra compra=null;
    private Fornecedor fornecedor = null;
    private Endereco endereco = null;
    /**
     * Creates new form CadastrarFornecedor
     */
    public CadastrarFornecedor() {
        initComponents();
    }

    public CadastrarFornecedor(Funcionario funcionario, Veiculo veiculo, Compra compra) {
       this.funcionario = funcionario;
       this.veiculo = veiculo;
       this.compra = compra;
       initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        tFBairro = new javax.swing.JTextField();
        tFRua = new javax.swing.JTextField();
        tFCidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tFNome = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tFNumero = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tFCEP = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tFDocumento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tFTelefone = new javax.swing.JTextField();
        CadBTConfirmar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jCTipoPessoa = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        tFComplemento = new javax.swing.JTextField();
        tFUF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(tFBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 240, -1));

        tFRua.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tFRuaFocusLost(evt);
            }
        });
        jPanel2.add(tFRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 240, -1));
        jPanel2.add(tFCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 240, -1));

        jLabel1.setText("Nome");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 23, -1, -1));

        jLabel3.setText("Bairro");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel2.setText("Rua");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel5.setText("Cidade");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        jPanel2.add(tFNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 20, 240, -1));

        jLabel14.setText("Número");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 158, -1, -1));
        jPanel2.add(tFNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 155, 118, -1));

        jLabel15.setText("UF");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 251, 22, -1));

        jLabel16.setText("CEP");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 309, -1, -1));
        jPanel2.add(tFCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 306, 240, -1));

        jLabel17.setText("CPF/CNPJ");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 23, -1, -1));

        tFDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFDocumentoActionPerformed(evt);
            }
        });
        tFDocumento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tFDocumentoFocusLost(evt);
            }
        });
        jPanel2.add(tFDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 20, 240, -1));

        jLabel9.setText("Telefone");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 306, -1, -1));
        jPanel2.add(tFTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 303, 207, -1));

        CadBTConfirmar.setText("Confirmar");
        CadBTConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadBTConfirmarActionPerformed(evt);
            }
        });
        jPanel2.add(CadBTConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 407, -1, 33));

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 404, -1, 39));

        jLabel18.setText("Tipo de pessoa");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jCTipoPessoa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONE", "FISICA", "JURIDICA" }));
        jCTipoPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTipoPessoaActionPerformed(evt);
            }
        });
        jPanel2.add(jCTipoPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 74, -1, -1));

        jLabel4.setText("Complemento");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 204, -1, -1));
        jPanel2.add(tFComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 193, 240, -1));
        jPanel2.add(tFUF, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 248, 84, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 830, 550));

        jLabel6.setText("Cadastro de Fornecedor");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tFDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFDocumentoActionPerformed
        
    }//GEN-LAST:event_tFDocumentoActionPerformed

    private void CadBTConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadBTConfirmarActionPerformed

        int flagfornecedor=0, flagEndereco=0;
        if (this.endereco == null)
            this.endereco = new Endereco();
        else
            flagEndereco=1;//para nao castrar endereco mais de uma vez
                    
        endereco.setBairro(this.tFBairro.getText().toUpperCase());
        endereco.setCep(tFCEP.getText());
        endereco.setCidade(tFCidade.getText().toUpperCase());
        endereco.setComplemento(tFComplemento.getText());
        endereco.setRua(tFRua.getText().toUpperCase());
        endereco.setUf(tFUF.getText().toUpperCase());
        
        String tipoPessoa= jCTipoPessoa.getSelectedItem().toString();
        
        if (this.fornecedor == null){
            this.fornecedor = new Fornecedor();
            this.fornecedor.setNome(this.tFNome.getText());
            try{
                this.fornecedor.setNumendereco(Integer.parseInt(this.tFNumero.getText()));
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Isira o numero da casa");
                this.fornecedor=null;
                return;
            }
            this.fornecedor.setTelefone(this.tFTelefone.getText());
             
        }else{
            flagfornecedor=1;           
        }
        this.fornecedor.setEndereco(null);
        
        //validar dados fornecedor
        FornecedorRN fornecedorRN = new FornecedorRN();
        String mensagem = fornecedorRN.cadastrarFornecedor(this.fornecedor, tipoPessoa, this.tFDocumento.getText());
        if (mensagem != "FK NULL"){
            if (flagfornecedor == 0)
                this.fornecedor=null;
            JOptionPane.showMessageDialog(null, mensagem);
            return;
        }
        
        //dados do fornecedor validado (só falta uma fk)
//-----------------------------------------------------------------------------------------------
 //salva endereco
         mensagem =null;
            if (flagEndereco==0){
                        EnderecoRN enderecoRN = new EnderecoRN();
                        mensagem = enderecoRN.cadastrarEndereco(endereco);
             
                        if (!mensagem.equals("CADASTROU")){
                            JOptionPane.showMessageDialog(null, mensagem);
                            return;
                        }else{
                            this.endereco = enderecoRN.buscarEndereco(this.endereco.getCidade(), this.endereco.getRua()); 
                            if (this.endereco!=null)
                                this.fornecedor.setEndereco(this.endereco);
                            else{
                                JOptionPane.showMessageDialog(null,"Erro ao buscar PK de endereco");
                                return;
                            }
                        }
            }else
                this.fornecedor.setEndereco(this.endereco);
             
        
 //------------------------------------------------------------------------------------------------       
        
        //salvar fornecedor
        if (flagfornecedor==0){ //se o fornecedor ja existir ele nao será cadastrado     
            mensagem = fornecedorRN.cadastrarFornecedor(fornecedor, tipoPessoa, this.tFDocumento.getText());
            if (!mensagem.equals("SALVOU")){
                JOptionPane.showMessageDialog(null, mensagem);
                return ;
            }
        }
        
 //-------------------buscar FK FORNECEDOR----------------------------------------------
        
        this.fornecedor = fornecedorRN.buscarFornecedor(this.tFDocumento.getText());
        
        if (this.fornecedor !=null){
            this.compra.setFornecedor(this.fornecedor);
            this.compra.setFuncionario(this.funcionario);
        }else
            return;
 //-----------------------------------------------------------------------------------------       
        //salvar compra
        mensagem=null;
        CompraRN compraRN = new CompraRN();
        mensagem = compraRN.cadastrarCompra(this.compra);
        if (!mensagem.equals("OK")){
            JOptionPane.showMessageDialog(null, mensagem);
            return;
        }else
            this.veiculo.setCompra(this.compra);
        
//---------------------------------------------------------
        //salvar o tipo de veiculo se preciso
        
        String tipo = this.veiculo.getTipoveiculo().getTipo();
        TipoVeiculoRN tipoVeiculoRN = new TipoVeiculoRN();
        Tipoveiculo tipoveiculo=null;
        tipoveiculo = tipoVeiculoRN.buscarVeiculo(tipo);
        if (tipoveiculo==null){
            tipoveiculo = new  Tipoveiculo();
            tipoveiculo.setTipo(tipo);
            tipoVeiculoRN.cadastrarTipoVeiculo(tipoveiculo);
        }
        this.veiculo.setTipoveiculo(tipoveiculo);
 //----------------------------------------------------------------------------------------------       
       //salvar o veiculo
        mensagem =null;
        VeiculoRN veiculoRN = new VeiculoRN();
        mensagem = veiculoRN.cadastrarVeiculo(this.veiculo);
        if (!mensagem.equals("OK")){
            JOptionPane.showMessageDialog(null, mensagem);
            return;
        }else
            JOptionPane.showMessageDialog(null, "Dados salvos com sucesso");
         TelaInicial telaIncial = new TelaInicial(this.funcionario);
         telaIncial.setVisible(true);
         this.setVisible(false);
  //-------------------------------------------------------------------------------   
         
        
    }//GEN-LAST:event_CadBTConfirmarActionPerformed

    private void tFDocumentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tFDocumentoFocusLost
        
        Fornecedor fornecedor = new Fornecedor();
        FornecedorRN fornecedorRN = new FornecedorRN();
        fornecedor = fornecedorRN.buscarFornecedor(this.tFDocumento.getText());
        if (fornecedor!=null){//encontrou os dados
            if (fornecedor.getCnpj()==null)
                this.tFDocumento.setText(fornecedor.getCpf());//somente um deles que existe
            else
                this.tFDocumento.setText(fornecedor.getCnpj());//somente um deles que existe
            
            this.tFNome.setText(fornecedor.getNome());
            this.tFNome.setEditable(false);
            this.tFNumero.setText(Integer.toString(fornecedor.getNumendereco()));
            this.tFNumero.setEditable(false);
            this.tFTelefone.setText(fornecedor.getTelefone());
            this.tFTelefone.setEditable(false); 
            this.fornecedor = fornecedor;
        }else{
            this.fornecedor=null;
            this.tFNome.setEditable(true);
            this.tFNumero.setEditable(true);
            this.tFTelefone.setEditable(true);
        }
    }//GEN-LAST:event_tFDocumentoFocusLost

    private void tFRuaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tFRuaFocusLost
        
        
        this.endereco = new Endereco();
        EnderecoRN enderecoRN = new EnderecoRN();
        this.endereco = enderecoRN.buscarEndereco(this.tFCidade.getText().toUpperCase(), this.tFRua.getText().toUpperCase());
        
        if(this.endereco != null){
            this.tFBairro.setText(this.endereco.getBairro());
            this.tFBairro.setEditable(false);
            this.tFCEP.setText(this.endereco.getCep());
            this.tFCEP.setEditable(false);
            this.tFComplemento.setText(this.endereco.getComplemento());
            this.tFComplemento.setEditable(false);
            this.tFUF.setText(this.endereco.getUf());
            this.tFUF.setEditable(false);            
        }else{
            this.tFBairro.setEditable(true);
            this.tFCEP.setEditable(true);
            this.tFComplemento.setEditable(true);
            this.tFUF.setEditable(true); 
            this.endereco=null;
        }
    }//GEN-LAST:event_tFRuaFocusLost

    private void jCTipoPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTipoPessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTipoPessoaActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        TelaInicial telaIncial = new TelaInicial(this.funcionario);
         telaIncial.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_jBCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarFornecedor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadBTConfirmar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JComboBox jCTipoPessoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tFBairro;
    private javax.swing.JTextField tFCEP;
    private javax.swing.JTextField tFCidade;
    private javax.swing.JTextField tFComplemento;
    private javax.swing.JTextField tFDocumento;
    private javax.swing.JTextField tFNome;
    private javax.swing.JTextField tFNumero;
    private javax.swing.JTextField tFRua;
    private javax.swing.JTextField tFTelefone;
    private javax.swing.JTextField tFUF;
    // End of variables declaration//GEN-END:variables
}
