/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import PacotePrincipal.*;
import RN.*;
import javax.swing.JOptionPane;

/**
 *
 * @author cliente
 */
public class CadastroEnderecos extends javax.swing.JFrame {
    private Cliente cliente=null;
    private Funcionario funcionario=null;
    private Fornecedor fornecedor=null;
    private Funcionario funcionarioLogado =null;
    private Endereco endereco =null;
    /**
     * Creates new form CadastroEnderecos
     */
    public CadastroEnderecos(Cliente cliente, Funcionario funcionarioLogado) {
        this.cliente=cliente;
        this.funcionarioLogado=funcionarioLogado;
        initComponents();
    }
    public CadastroEnderecos(Funcionario funcionarioLogado, Funcionario funcionario) {
        this.funcionarioLogado=funcionarioLogado;
        this.funcionario=funcionario;
        initComponents();
    }
    public CadastroEnderecos(Funcionario funcionarioLogado, Fornecedor fornecedor) {
        this.funcionarioLogado=funcionarioLogado;
        this.fornecedor=fornecedor;
        initComponents();
    }
    
    public CadastroEnderecos() { 
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rua = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bairro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cidade = new javax.swing.JTextField();
        cep = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        complemento = new javax.swing.JTextField();
        botaoConfirmar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        uf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rua.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ruaFocusLost(evt);
            }
        });
        getContentPane().add(rua, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 120, -1));

        jLabel2.setText("Rua");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel3.setText("Bairro");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
        getContentPane().add(bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 120, -1));

        jLabel5.setText("Cidade");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        getContentPane().add(cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 120, -1));
        getContentPane().add(cep, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 120, -1));

        jLabel15.setText("UF");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 151, 22, -1));

        jLabel16.setText("CEP");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel1.setText("Complemento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 100, -1, -1));

        complemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complementoActionPerformed(evt);
            }
        });
        getContentPane().add(complemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 97, 207, -1));

        botaoConfirmar.setText("Confirmar");
        botaoConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 286, -1, -1));

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 286, -1, -1));
        getContentPane().add(uf, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 148, 50, -1));

        jLabel4.setText("Numero");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 52, -1, -1));
        getContentPane().add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 49, 103, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void complementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_complementoActionPerformed

    private void botaoConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarActionPerformed
        String mensagem=null;    
        if (this.endereco == null){//se entrar endereco nao existe
                this.endereco = new Endereco(); 
                endereco.setRua(rua.getText());
                endereco.setBairro(bairro.getText());
                endereco.setComplemento(complemento.getText());
                endereco.setCidade(cidade.getText());
                endereco.setUf(uf.getText());
                endereco.setCep(cep.getText());

                EnderecoRN enderecoRN = new EnderecoRN();
                mensagem = enderecoRN.cadastrarEndereco(endereco);
                if (!mensagem.equals("CADASTROU")){
                    JOptionPane.showMessageDialog(null,mensagem);
                    return;
                }else{//bscar fk de endereco
                    
                }      
        } 
        
       try{  //erro na conversao de numero
                if(cliente!=null){
                    cliente.setNumendereco(Integer.parseInt(numero.getText()));
                    cliente.setEndereco(this.endereco);
                    ClienteRN clienteRN = new ClienteRN();
                    mensagem = clienteRN.cadastrarCliente(cliente);
                    JOptionPane.showMessageDialog(null,mensagem);
                }
                else if(funcionario!=null){
                    funcionario.setNumendereco(Integer.parseInt(numero.getText()));
                    funcionario.setEndereco(this.endereco);
                    FuncionarioRN funcionarioRN = new FuncionarioRN();
                    mensagem = funcionarioRN.cadastrarFuncionario(funcionario);
                    JOptionPane.showMessageDialog(null,mensagem);
                }
                else{
                    fornecedor.setNumendereco(Integer.parseInt(numero.getText()));
                    fornecedor.setEndereco(this.endereco);             
                    FornecedorRN fornecedorRN = new FornecedorRN();
                    mensagem = fornecedorRN.cadastrarFornecedor(fornecedor);
                    JOptionPane.showMessageDialog(null,mensagem);
                }
        }catch(NumberFormatException e){
               JOptionPane.showMessageDialog(null,"Erro: "+e.getMessage());    
        }
            
    }//GEN-LAST:event_botaoConfirmarActionPerformed

    private void ruaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ruaFocusLost
        this.endereco = new Endereco();
        EnderecoRN enderecoRN = new EnderecoRN();
        this.endereco = enderecoRN.buscarEndereco(this.cidade.getText().toUpperCase(), this.rua.getText().toUpperCase());
        
        if(this.endereco != null){
            this.bairro.setText(this.endereco.getBairro());
            this.bairro.setEditable(false);
            this.cep.setText(this.endereco.getCep());
            this.cep.setEditable(false);
            this.complemento.setText(this.endereco.getComplemento());
            this.complemento.setEditable(false);
            this.uf.setText(this.endereco.getUf());
            this.uf.setEditable(false);            
        }else{
            this.bairro.setEditable(true);
            this.cep.setEditable(true);
            this.complemento.setEditable(true);
            this.uf.setEditable(true); 
            this.endereco=null;
        }
    }//GEN-LAST:event_ruaFocusLost

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Tela Inicial") == 0 ){ //0 é o sim
            TelaInicial telaInicial = new TelaInicial(this.funcionarioLogado);
            telaInicial.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_botaoCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroEnderecos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroEnderecos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroEnderecos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroEnderecos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroEnderecos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairro;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoConfirmar;
    private javax.swing.JTextField cep;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField complemento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField rua;
    private javax.swing.JTextField uf;
    // End of variables declaration//GEN-END:variables
}
