/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import PacotePrincipal.*;
import RN.TaxaRN;
import RN.TipoVeiculoRN;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author cliente
 */
public class CadastrarTaxa extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarTaxa
     */
    public CadastrarTaxa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        diario = new javax.swing.JTextField();
        semanal = new javax.swing.JTextField();
        mensal = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        taxaExtra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        valorKm = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        dataInicio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dataFim = new javax.swing.JTextField();
        tipoDoVeiculo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Adiciona taxa");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 11, -1, -1));

        jLabel10.setText("Valor de aluguel");

        jLabel12.setText("Diário");

        jLabel13.setText("Semanal");

        jLabel14.setText("Mensal");

        diario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10)
                    .addComponent(diario, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(semanal)
                    .addComponent(mensal))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(diario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(semanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(mensal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel17.setText("Taxa extra de seguro");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));
        getContentPane().add(taxaExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 124, -1));

        jLabel2.setText("Valor por km");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        jLabel9.setText("Tipo de veiculo");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 110, -1));
        getContentPane().add(valorKm, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 124, -1));

        jButton2.setText("Cancelar");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, -1, -1));

        jLabel3.setText("Data inicial");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));
        getContentPane().add(dataInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 131, -1));

        jLabel4.setText("Data Final");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));
        getContentPane().add(dataFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 131, -1));
        getContentPane().add(tipoDoVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 60, 180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            Taxa taxa = new Taxa();
            Tipoveiculo tipoVeiculo = new Tipoveiculo();
            tipoVeiculo.setTipo(tipoDoVeiculo.getText());
            TipoVeiculoRN tipoVeiculoRN = new TipoVeiculoRN();
            String mensagem = tipoVeiculoRN.cadastrarTipoVeiculo(tipoVeiculo);
            
            try{    //Formato data do VO é do tipo Date 
                Date data1 = new SimpleDateFormat("dd/MM/yyyy").parse(dataInicio.getText()); 
                Date data2 = new SimpleDateFormat("dd/MM/yyyy").parse(dataFim.getText()); 
                taxa.setDatainicialtaxa(data1);
                taxa.setDatafinaltaxa(data2);
            }catch(ParseException erroData){
                JOptionPane.showMessageDialog(null,"Formato de data inválido");
            }            
            mensagem ="ok";
            taxa.setTipoveiculo(tipoVeiculo);
            TaxaRN taxaRN = new TaxaRN();
            boolean teste = taxaRN.verificaDia(diario.getText());
            if(teste==false){
                    taxa.setTipotaxa("DIARIO"); 
                    BigDecimal bd = new BigDecimal(diario.getText());
                     taxa.setValortaxa(bd);
                     mensagem = taxaRN.cadastrarTaxa(taxa);
            }
            teste = taxaRN.verificaDia(semanal.getText());
            if(teste==false){
                    taxa.setTipotaxa("SEMANAL"); 
                     BigDecimal bd = new BigDecimal(semanal.getText());
                     taxa.setValortaxa(bd);
                     mensagem = taxaRN.cadastrarTaxa(taxa);
            }
            teste = taxaRN.verificaDia(mensal.getText());
            if(teste==false){
                    taxa.setTipotaxa("MENSAL");  
                    BigDecimal bd = new BigDecimal(mensal.getText());
                     taxa.setValortaxa(bd);
                     mensagem = taxaRN.cadastrarTaxa(taxa);
            }
            teste = taxaRN.verificaDia(taxaExtra.getText());
            if(teste==false){
                    taxa.setTipotaxa("TAXA EXTRA"); 
                     BigDecimal bd = new BigDecimal(taxaExtra.getText());
                     taxa.setValortaxa(bd);
                     mensagem = taxaRN.cadastrarTaxa(taxa);
            }
            teste = taxaRN.verificaDia(valorKm.getText());
            if(teste==false){
                     taxa.setTipotaxa("VALOR POR KM"); 
                     BigDecimal bd = new BigDecimal(valorKm.getText());
                     taxa.setValortaxa(bd);
                     mensagem = taxaRN.cadastrarTaxa(taxa);
            }
            if(!("ok").equals(mensagem))
                    JOptionPane.showMessageDialog(null, mensagem);
            else
                    JOptionPane.showMessageDialog(null, "Deve-se cadastrar um tipo de taxa");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarTaxa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarTaxa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarTaxa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarTaxa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarTaxa().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dataFim;
    private javax.swing.JTextField dataInicio;
    private javax.swing.JTextField diario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mensal;
    private javax.swing.JTextField semanal;
    private javax.swing.JTextField taxaExtra;
    private javax.swing.JTextField tipoDoVeiculo;
    private javax.swing.JTextField valorKm;
    // End of variables declaration//GEN-END:variables
}
