/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import PacotePrincipal.Endereco;
import PacotePrincipal.Fornecedor;
import RN.EnderecoRN;
import RN.FornecedorRN;
import javax.swing.JOptionPane;

/**
 *
 * @author a1257072
 */
public class DadosFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form DadosFornecedor
     */
    public DadosFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        complemento = new javax.swing.JTextField();
        rua = new javax.swing.JTextField();
        tipoPessoa = new javax.swing.JTextField();
        bairro = new javax.swing.JTextField();
        cidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        documento = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cep = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        telefone = new javax.swing.JTextField();
        botaoOk = new javax.swing.JButton();
        DFBTSair = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        dataNasc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        senha = new javax.swing.JTextField();
        uf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        DFBTConfirmar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(complemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 240, -1));
        jPanel2.add(rua, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 240, -1));
        jPanel2.add(tipoPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 190, -1));
        jPanel2.add(bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 240, -1));
        jPanel2.add(cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 240, -1));

        jLabel1.setText("CPF/CNPJ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabel3.setText("Bairro");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 30, 20));

        jLabel2.setText("Rua");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel5.setText("Cidade");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel6.setText("Complemento");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 20));

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        jPanel2.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 240, -1));

        jLabel14.setText("Número");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));
        jPanel2.add(documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 290, -1));

        jLabel15.setText("UF");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));

        jLabel16.setText("CEP");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));
        jPanel2.add(cep, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 207, -1));

        jLabel9.setText("Telefone");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));
        jPanel2.add(telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 207, -1));

        botaoOk.setText("OK");
        botaoOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOkActionPerformed(evt);
            }
        });
        jPanel2.add(botaoOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        DFBTSair.setText("Sair");
        jPanel2.add(DFBTSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 84, -1));

        jLabel10.setText("Data de nascimento");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        jPanel2.add(dataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 240, -1));

        jLabel8.setText("Login");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, 20));
        jPanel2.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 240, -1));

        jLabel11.setText("Senha");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, -1, -1));
        jPanel2.add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 203, -1));

        uf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ufActionPerformed(evt);
            }
        });
        jPanel2.add(uf, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 26, -1));

        jLabel13.setText("Tipo de pessoa");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        jLabel4.setText("Nome");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));
        jPanel2.add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 118, -1));

        DFBTConfirmar1.setText("Confirmar");
        DFBTConfirmar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DFBTConfirmar1ActionPerformed(evt);
            }
        });
        jPanel2.add(DFBTConfirmar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 882, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(125, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoOkActionPerformed

    private void ufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ufActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void DFBTConfirmar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DFBTConfirmar1ActionPerformed
            Endereco endereco = new Endereco(); 
            Fornecedor fornecedor = new Fornecedor();
            endereco.setRua(rua.getText());
            endereco.setBairro(complemento.getText());
            endereco.setComplemento(complemento.getText());
            endereco.setCidade(cidade.getText());
            endereco.setUf(uf.getText());
            endereco.setCep(cep.getText());

            EnderecoRN enderecoRN = new EnderecoRN();
            String mensagem = enderecoRN.atualizarEndereco(endereco);
            fornecedor.setNome(nome.getText());
            fornecedor.setTelefone(telefone.getText());
                   
            fornecedor.setNumendereco(Integer.parseInt(numero.getText()));
            fornecedor.setEndereco(endereco);             
            FornecedorRN fornecedorRN = new FornecedorRN();
            mensagem = fornecedorRN.atualizarFornecedor(fornecedor);
            JOptionPane.showMessageDialog(null,mensagem);
    }//GEN-LAST:event_DFBTConfirmar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DadosFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DadosFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DadosFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DadosFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DadosFornecedor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DFBTConfirmar1;
    private javax.swing.JButton DFBTSair;
    private javax.swing.JTextField bairro;
    private javax.swing.JButton botaoOk;
    private javax.swing.JTextField cep;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField complemento;
    private javax.swing.JTextField dataNasc;
    private javax.swing.JTextField documento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField login;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField rua;
    private javax.swing.JTextField senha;
    private javax.swing.JTextField telefone;
    private javax.swing.JTextField tipoPessoa;
    private javax.swing.JTextField uf;
    // End of variables declaration//GEN-END:variables
}
