/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import PacotePrincipal.Endereco;
import PacotePrincipal.Funcionario;
import PacotePrincipal.Setor;
import RN.EnderecoRN;
import RN.FuncionarioRN;
import RN.SetorRN;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author cliente
 */
public class DadosFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form DadosFuncionario
     */
    public DadosFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        bairro = new javax.swing.JTextField();
        rua = new javax.swing.JTextField();
        tipo = new javax.swing.JTextField();
        cidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cep = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        telefone = new javax.swing.JTextField();
        DFBTConfirmar = new javax.swing.JButton();
        DFBTSair = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        dataNasc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        senha = new javax.swing.JTextField();
        uf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        complemento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        setor = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        documento = new javax.swing.JTextField();
        DFBTOK = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 200, -1));
        jPanel2.add(rua, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 68, 240, -1));
        jPanel2.add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 247, 240, -1));
        jPanel2.add(cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 168, 240, -1));

        jLabel1.setText("Nome");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3, -1, -1));

        jLabel3.setText("Bairro");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        jLabel2.setText("Rua");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 71, -1, -1));

        jLabel5.setText("Cidade");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 171, -1, -1));
        jPanel2.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 0, 240, -1));

        jLabel14.setText("Número");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 71, -1, -1));
        jPanel2.add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 68, 118, -1));

        jLabel15.setText("UF");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        jLabel16.setText("CEP");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 206, -1, -1));
        jPanel2.add(cep, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 206, 207, -1));

        jLabel9.setText("Telefone");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));
        jPanel2.add(telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 207, -1));

        DFBTConfirmar.setText("Confirmar");
        DFBTConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DFBTConfirmarActionPerformed(evt);
            }
        });
        jPanel2.add(DFBTConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 387, -1, -1));

        DFBTSair.setText("Sair");
        jPanel2.add(DFBTSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 387, 84, -1));

        jLabel10.setText("Data de nascimento");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 41, -1, -1));
        jPanel2.add(dataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 38, 240, -1));

        jLabel8.setText("Login");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 307, -1, -1));
        jPanel2.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 306, 240, -1));

        jLabel11.setText("Senha");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 309, -1, -1));
        jPanel2.add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 306, 203, -1));

        uf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ufActionPerformed(evt);
            }
        });
        jPanel2.add(uf, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 26, -1));

        jLabel13.setText("Tipo de funcionário");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel4.setText("Complemento");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        jPanel2.add(complemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 230, -1));

        jLabel6.setText("Setor");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, -1));
        jPanel2.add(setor, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 180, -1));

        jLabel17.setText("Informar CPF");

        documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentoActionPerformed(evt);
            }
        });

        DFBTOK.setText("OK");

        jLabel12.setText("Dados do funcionário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel17)
                        .addGap(71, 71, 71)
                        .addComponent(documento, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(DFBTOK))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DFBTOK))
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_documentoActionPerformed

    private void ufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ufActionPerformed

    private void DFBTConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DFBTConfirmarActionPerformed
            Endereco endereco = new Endereco(); 
            Setor setor1 = new Setor();
            Funcionario funcionario = new Funcionario();
            endereco.setRua(rua.getText());
            endereco.setBairro(bairro.getText());
            endereco.setComplemento(complemento.getText());
            endereco.setCidade(cidade.getText());
            endereco.setUf(uf.getText());
            endereco.setCep(cep.getText());

            EnderecoRN enderecoRN = new EnderecoRN();
            String mensagem = enderecoRN.atualizarEndereco(endereco);
            
            funcionario.setNome(nome.getText());
            try{    
                Date data1 = new SimpleDateFormat("dd/MM/yyyy").parse(dataNasc.getText()); 
                funcionario.setDatanascimento(data1);
            }catch(ParseException erroData){
                JOptionPane.showMessageDialog(null,"Formato de data inválido");
            }     
            funcionario.setTelefone(telefone.getText());
            funcionario.setTipo(tipo.getText());
            funcionario.setLogin(login.getText());
            funcionario.setSenha(senha.getText());
            
            setor1.setSetor(setor.getText());
            SetorRN setorRN = new SetorRN();
            mensagem = setorRN.atualizarSetor(setor1);
            
            funcionario.setSetor(setor1);
            funcionario.setNumendereco(Integer.parseInt(numero.getText()));
            funcionario.setEndereco(endereco);
            FuncionarioRN funcionarioRN = new FuncionarioRN();
            mensagem = funcionarioRN.atualizarFuncionario(funcionario);
            JOptionPane.showMessageDialog(null,mensagem);
    }//GEN-LAST:event_DFBTConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DadosFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DadosFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DadosFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DadosFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DadosFuncionario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DFBTConfirmar;
    private javax.swing.JButton DFBTOK;
    private javax.swing.JButton DFBTSair;
    private javax.swing.JTextField bairro;
    private javax.swing.JTextField cep;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField complemento;
    private javax.swing.JTextField dataNasc;
    private javax.swing.JTextField documento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField login;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField rua;
    private javax.swing.JTextField senha;
    private javax.swing.JTextField setor;
    private javax.swing.JTextField telefone;
    private javax.swing.JTextField tipo;
    private javax.swing.JTextField uf;
    // End of variables declaration//GEN-END:variables
}
