/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import PacotePrincipal.Funcionario;

/**
 *
 * @author cliente
 */
public class SetorVendas extends javax.swing.JFrame {
    private Funcionario funcionario;
    /**
     * Creates new form SetorVendas
     */
    public SetorVendas() {
        initComponents();
    }

    public SetorVendas(Funcionario funcionario) {
        this.funcionario = funcionario;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        VTFPlaca = new javax.swing.JTextField();
        VBTOK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TPVenda = new javax.swing.JTextPane();
        VBTConfirmar = new javax.swing.JButton();
        VBTCancelar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        VRBSim = new javax.swing.JRadioButton();
        VRBNao = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        vTFData = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        VTFValor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Placa");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 34, -1, -1));
        getContentPane().add(VTFPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 31, 219, -1));

        VBTOK.setText("OK");
        getContentPane().add(VBTOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 30, -1, -1));

        jScrollPane1.setViewportView(TPVenda);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 71, 496, 262));

        VBTConfirmar.setText("Confirmar");
        getContentPane().add(VBTConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 522, -1, 40));

        VBTCancelar.setText("Cancelar");
        VBTCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VBTCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(VBTCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 522, 84, 40));

        jLabel16.setText("Cliente já cadastrado?");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 458, -1, -1));

        VRBSim.setText("Sim");
        VRBSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VRBSimActionPerformed(evt);
            }
        });
        getContentPane().add(VRBSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 454, -1, -1));

        VRBNao.setText("Não");
        getContentPane().add(VRBNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 454, -1, -1));

        jLabel2.setText("Data atual");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 378, -1, -1));
        getContentPane().add(vTFData, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 375, 161, -1));

        jLabel3.setText("Valor");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 413, -1, -1));
        getContentPane().add(VTFValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 413, 161, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VRBSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VRBSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VRBSimActionPerformed

    private void VBTCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VBTCancelarActionPerformed
        TelaInicial telaInicial = new TelaInicial(this.funcionario);
        telaInicial.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VBTCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetorVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetorVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetorVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetorVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetorVendas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane TPVenda;
    private javax.swing.JButton VBTCancelar;
    private javax.swing.JButton VBTConfirmar;
    private javax.swing.JButton VBTOK;
    private javax.swing.JRadioButton VRBNao;
    private javax.swing.JRadioButton VRBSim;
    private javax.swing.JTextField VTFPlaca;
    private javax.swing.JTextField VTFValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField vTFData;
    // End of variables declaration//GEN-END:variables
}
