/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author cliente
 */
import PacotePrincipal.*;
import RN.AluguelRN;
import RN.ClienteRN;
import RN.*;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
public class SetorCobranca extends javax.swing.JFrame {
    private Aluguel aluguel;
    private Funcionario funcionario;
    private float kmAntiga;
    /**
     * Creates new form SetorCobranca
     */
    public SetorCobranca(Aluguel aluguel, Funcionario funcionario, float kmAntiga) {
        this.funcionario = funcionario;
        this.aluguel = aluguel;
        initComponents();
    }
    public SetorCobranca(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tFValor = new javax.swing.JTextField();
        jBDarBaixa = new javax.swing.JButton();
        jBEnviarBoleto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jBCalcular = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Valor Aluguel");

        jBDarBaixa.setText("Dar Baixa");
        jBDarBaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDarBaixaActionPerformed(evt);
            }
        });

        jBEnviarBoleto.setText("Enviar boleto");
        jBEnviarBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnviarBoletoActionPerformed(evt);
            }
        });

        jLabel3.setText("Finanças");

        jBCalcular.setText("Calcular");
        jBCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalcularActionPerformed(evt);
            }
        });

        jButton1.setText("Tela Incial");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jBDarBaixa)
                        .addGap(39, 39, 39)
                        .addComponent(jBEnviarBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(33, 33, 33)
                        .addComponent(tFValor, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(jBCalcular)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(195, 195, 195)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tFValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCalcular)
                    .addComponent(jLabel2))
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBDarBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEnviarBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalcularActionPerformed
        AluguelRN aluguelRN = new AluguelRN();
        String valorAluguel = aluguelRN.calcularAluguel(this.aluguel,this.kmAntiga);
        this.tFValor.setText(valorAluguel);
    }//GEN-LAST:event_jBCalcularActionPerformed

    private void jBDarBaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDarBaixaActionPerformed
        Date data = new Date();
        String formaPagamento = JOptionPane.showInputDialog("Forma de Pagamento","digite aqui");
        String dataPagamento =  JOptionPane.showInputDialog("Data Pagamento ex.: 25/12/2013:","digite aqui"); 
        try{
            data = new SimpleDateFormat("dd/MM/yyyy").parse(dataPagamento); 
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Insira a data Corretamente");
            return;
        }
        this.aluguel.setDatadevolucao(data);
        this.aluguel.setFormapagamento(formaPagamento);
        AluguelRN aluguelRN = new AluguelRN();
        String mensagem = aluguelRN.darBaixa(this.aluguel);
        if (!mensagem.equals("OK")){
            JOptionPane.showMessageDialog(null, "Erro ao dar Baixa tente novamente");
            return;
        }
        JOptionPane.showMessageDialog(null, "Dado Baixa Com sucesso");
            
    }//GEN-LAST:event_jBDarBaixaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Tela Inicial") == 0 ){ //0 é o sim
            TelaInicial telaInicial = new TelaInicial(this.funcionario);
            telaInicial.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBEnviarBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnviarBoletoActionPerformed
         ClienteRN clienteRN = new ClienteRN();
         Cliente cliente =new Cliente();
         cliente = clienteRN.buscarEmailCliente(this.aluguel);
         if (cliente == null){
             JOptionPane.showMessageDialog(null, "Email nao encontrado");
             return;
         }
         JOptionPane.showMessageDialog(null, "Email: "+cliente.getEmail());
    }//GEN-LAST:event_jBEnviarBoletoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetorCobranca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetorCobranca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetorCobranca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetorCobranca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetorCobranca().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCalcular;
    private javax.swing.JButton jBDarBaixa;
    private javax.swing.JButton jBEnviarBoleto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tFValor;
    // End of variables declaration//GEN-END:variables
}
