/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import PacotePrincipal.*;
import RN.*;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author cliente
 */
public class SetorEntrada extends javax.swing.JFrame {
   private Veiculo veiculo;
   private Funcionario funcionario;
  
    /**
     * Creates new form SetorEntrada
     */
    public SetorEntrada() {
        initComponents();
    }
    public SetorEntrada(Funcionario funcionario) {
        this.funcionario = funcionario;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        tFPlaca = new javax.swing.JTextField();
        jBConfirmar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tFDataEntrega = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tFKmAtual = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tFMostrarDadosVeiculo = new javax.swing.JTextPane();
        botaoOKbuscarCarro = new javax.swing.JButton();
        jBAdicionarmanutencao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Placa");

        tFPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFPlacaActionPerformed(evt);
            }
        });

        jBConfirmar.setText("Confirmar");
        jBConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmarActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");

        jLabel10.setText("Informações da recepção");

        jLabel11.setText("Data Entrega");

        jLabel12.setText("Km Atual");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tFDataEntrega)
                            .addComponent(tFKmAtual, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(tFDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tFKmAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(tFMostrarDadosVeiculo);

        botaoOKbuscarCarro.setText("OK");
        botaoOKbuscarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOKbuscarCarroActionPerformed(evt);
            }
        });

        jBAdicionarmanutencao.setText("Adicionar Manutenção");
        jBAdicionarmanutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarmanutencaoActionPerformed(evt);
            }
        });

        jLabel1.setText("Setor de entrada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(99, 99, 99)
                                    .addComponent(tFPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(84, 84, 84)
                                    .addComponent(botaoOKbuscarCarro)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBConfirmar)
                                .addGap(31, 31, 31)
                                .addComponent(jBAdicionarmanutencao)
                                .addGap(54, 54, 54)
                                .addComponent(jBCancelar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel1)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tFPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(botaoOKbuscarCarro))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAdicionarmanutencao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoOKbuscarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOKbuscarCarroActionPerformed
       //ATENCAO setar o atributo veiculo dessa classe com o veiculo buscado no banco
        //porque ele é enviado p/ o setor de manuteção.
        //this.veiculo = veiculo; //sendo que this.veiculo é o atributo dessa tela, e veiculo é veiculo retornado do banco quando vc colocar pra buscar pela placa
        this.tFDataEntrega.setEditable(false);
        this.tFKmAtual.setEditable(false);
        this.tFMostrarDadosVeiculo.setEditable(false);
        this.jBConfirmar.setEnabled(false);
        this.jBAdicionarmanutencao.setEnabled(false);
        String placa = tFPlaca.getText();
        VeiculoRN veiculoRN = new VeiculoRN();
        this.veiculo = veiculoRN.buscarVeiculo(placa);
        
        if (this.veiculo == null){
            this.tFMostrarDadosVeiculo.setText("Veículo não encontrado");           
        }else{           
            String mostrarVeiculo = 
                    "Placa: "+this.veiculo.getPlaca()+"\nStatus: "+this.veiculo.getStatus()+
                    "\nChassi: "+this.veiculo.getChassi()+"\nCombustivel: "+this.veiculo.getCombustivel()+"\nCor: "+this.veiculo.getCor()+
                    "\nModelo: "+this.veiculo.getModelo()+"\nAno: "+this.veiculo.getAno()+
                    "\nKilometragem: "+this.veiculo.getKilometragem();
            tFMostrarDadosVeiculo.setText(mostrarVeiculo);                    
                    
            this.tFDataEntrega.setEditable(true);
            this.tFKmAtual.setEditable(true);
            this.jBConfirmar.setEnabled(true);
            this.jBAdicionarmanutencao.setEnabled(true);  
        }
    }//GEN-LAST:event_botaoOKbuscarCarroActionPerformed

    private void tFPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFPlacaActionPerformed

    private void jBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarActionPerformed
        float kmAntiga;
        
        Date dataEntrega=null;
        try{    //Formato data do VO é do tipo Date 
           dataEntrega = new SimpleDateFormat("dd/MM/yyyy").parse(tFDataEntrega.getText()); 
        }catch(Exception erro){
            JOptionPane.showMessageDialog(null,"Erro na data: "+erro.getMessage());
            return;
        }
            String mensagem="";
            VeiculoRN veiculoRN= new VeiculoRN();
 
           Aluguel aluguel = new Aluguel();
           AluguelRN aluguelRN = new AluguelRN();
           aluguel = aluguelRN.buscarUmAluguelSemDataDevolucao(this.veiculo);
           
           if (aluguel!=null){//se encontrou aluguel entao será redireciondo para o setor de cobrança passando  o aluguel como parametro para o contrutor
               kmAntiga = this.veiculo.getKilometragem().floatValue();//para usar no calculo do aluguel
               this.veiculo.setStatus("DISPONIVEL");
               mensagem = veiculoRN.atualizarVeiculo(this.veiculo, this.tFKmAtual.getText());
               
                if (mensagem != "atualizou"){
                    JOptionPane.showMessageDialog(null,""+mensagem);
                    return;
                }
                
                        
               
                //adiciona data de entrega no aluguel
               mensagem = aluguelRN.atualizarDataDevolucao(dataEntrega, aluguel); 
                
                if (mensagem != "OK"){//erro ao atualizar  
                    JOptionPane.showMessageDialog(null,""+mensagem);
                    return;
                }
                //JOptionPane.showMessageDialog(null,"data Devolucao: "+aluguel.getDatadevolucao());
                
               
           }else{
                JOptionPane.showMessageDialog(null,"Aluguel nao encontrado");
                return;
           }
           
           
        
         SetorCobranca setorCobranca = new SetorCobranca(aluguel, this.funcionario, kmAntiga);
         setorCobranca.setVisible(true);
         this.setVisible(false);//oculta essa tela "setor de entrada"
        
        //JOptionPane.showMessageDialog(null,"CodAluguel: "+aluguel.getCodaluguel());
        
    }//GEN-LAST:event_jBConfirmarActionPerformed

    private void jBAdicionarmanutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarmanutencaoActionPerformed
        SetorManutencao setorManutencao = new SetorManutencao(this.veiculo, this.funcionario);
        setorManutencao.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBAdicionarmanutencaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetorEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetorEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetorEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetorEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetorEntrada().setVisible(true);
            }
        });
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoOKbuscarCarro;
    private javax.swing.JButton jBAdicionarmanutencao;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tFDataEntrega;
    private javax.swing.JTextField tFKmAtual;
    private javax.swing.JTextPane tFMostrarDadosVeiculo;
    private javax.swing.JTextField tFPlaca;
    // End of variables declaration//GEN-END:variables
}
