/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import PacotePrincipal.*;

/**
 *
 * @author cliente
 */
public class TelaDiretor extends javax.swing.JFrame {
    private Funcionario funcionario;
    
    public TelaDiretor() {
        initComponents();
    }
    
    public TelaDiretor(Funcionario funcionario) {
        this.funcionario = funcionario;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTDemanda = new javax.swing.JButton();
        BTDadosPromocao = new javax.swing.JButton();
        BTCadastrarPromocao = new javax.swing.JButton();
        BTVerificar = new javax.swing.JButton();
        BTCadastraFuncionario = new javax.swing.JButton();
        BTDadosFuncionario = new javax.swing.JButton();
        BTNaoConfirmado = new javax.swing.JButton();
        btRealizarBaixa = new javax.swing.JButton();
        btAdicionaTaxa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTDemanda.setText("Verificar demanda");
        getContentPane().add(BTDemanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 75, -1, 37));

        BTDadosPromocao.setText("Dados de promoção");
        getContentPane().add(BTDadosPromocao, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, 37));

        BTCadastrarPromocao.setText("Cadastro de promoções");
        getContentPane().add(BTCadastrarPromocao, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, 35));

        BTVerificar.setText("Informações de taxas");
        getContentPane().add(BTVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 155, 146, 32));

        BTCadastraFuncionario.setText("Cadastrar funcionário");
        BTCadastraFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTCadastraFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(BTCadastraFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 168, 32));

        BTDadosFuncionario.setText("Dados dos funcionários");
        BTDadosFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTDadosFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(BTDadosFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 146, 30));

        BTNaoConfirmado.setText("Pagamento não confirmados");
        getContentPane().add(BTNaoConfirmado, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 247, 188, 38));

        btRealizarBaixa.setText("Realizar baixa do pagamento");
        getContentPane().add(btRealizarBaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 245, 195, 40));

        btAdicionaTaxa.setText("Adicionar taxas");
        btAdicionaTaxa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionaTaxaActionPerformed(evt);
            }
        });
        getContentPane().add(btAdicionaTaxa, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 351, -1, 39));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTDadosFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTDadosFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTDadosFuncionarioActionPerformed

    private void btAdicionaTaxaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionaTaxaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAdicionaTaxaActionPerformed

    private void BTCadastraFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTCadastraFuncionarioActionPerformed
        CadastrarFuncionario cadastrarFuncionario = new CadastrarFuncionario(this.funcionario);
        cadastrarFuncionario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTCadastraFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDiretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDiretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDiretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDiretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDiretor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTCadastraFuncionario;
    private javax.swing.JButton BTCadastrarPromocao;
    private javax.swing.JButton BTDadosFuncionario;
    private javax.swing.JButton BTDadosPromocao;
    private javax.swing.JButton BTDemanda;
    private javax.swing.JButton BTNaoConfirmado;
    private javax.swing.JButton BTVerificar;
    private javax.swing.JButton btAdicionaTaxa;
    private javax.swing.JButton btRealizarBaixa;
    // End of variables declaration//GEN-END:variables
}
