/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import PacotePrincipal.Funcionario;
import RN.LoginRN;
import javax.swing.JOptionPane;

/**
 *
 * @author cliente
 */
public class TelaInicial extends javax.swing.JFrame {

    public TelaInicial() {
        initComponents();
    }
    private Funcionario funcionario;
    /**
     * Creates new form TelaInicial
     */
   
    public TelaInicial(Funcionario funcionario) {
        this.funcionario = funcionario;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jBCompra = new javax.swing.JButton();
        jBVenda = new javax.swing.JButton();
        jBLocacao = new javax.swing.JButton();
        jBRecepcao = new javax.swing.JButton();
        jBConsulta = new javax.swing.JButton();
        jBAtualizar = new javax.swing.JButton();
        jBDiretor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bem Vindo");

        jBCompra.setText("Compra");
        jBCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCompraActionPerformed(evt);
            }
        });

        jBVenda.setText("Venda");
        jBVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVendaActionPerformed(evt);
            }
        });

        jBLocacao.setText("Locação");
        jBLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLocacaoActionPerformed(evt);
            }
        });

        jBRecepcao.setText("Recepção");
        jBRecepcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRecepcaoActionPerformed(evt);
            }
        });

        jBConsulta.setText("Consultar");
        jBConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultaActionPerformed(evt);
            }
        });

        jBAtualizar.setText("Atualizar veículo");
        jBAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtualizarActionPerformed(evt);
            }
        });

        jBDiretor.setText("Diretor");
        jBDiretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDiretorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBCompra)
                            .addComponent(jBRecepcao))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBAtualizar)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jBVenda)))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBConsulta)
                            .addComponent(jBLocacao)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jBDiretor)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCompra)
                    .addComponent(jBVenda)
                    .addComponent(jBLocacao))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBConsulta)
                    .addComponent(jBRecepcao)
                    .addComponent(jBAtualizar))
                .addGap(54, 54, 54)
                .addComponent(jBDiretor)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRecepcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRecepcaoActionPerformed
       SetorEntrada setorEntrada = new SetorEntrada(this.funcionario);
       setorEntrada.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jBRecepcaoActionPerformed

    private void jBVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVendaActionPerformed
        SetorVendas setorVenda = new SetorVendas(this.funcionario);
        setorVenda.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBVendaActionPerformed

    private void jBLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLocacaoActionPerformed
        SetorLocacao setorLocacao = new SetorLocacao(this.funcionario);
        setorLocacao.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBLocacaoActionPerformed

    private void jBAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizarActionPerformed
       AtualizarVeiculo atualizarVeiculo = new AtualizarVeiculo(this.funcionario);
       atualizarVeiculo.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jBAtualizarActionPerformed

    private void jBConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultaActionPerformed
        Consulta consulta = new Consulta(this.funcionario);
        consulta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBConsultaActionPerformed

    private void jBCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCompraActionPerformed
        LoginRN loginRN = new LoginRN();
        if (loginRN.solicitarAcessoDiretor(this.funcionario)){
            SetorCompras setorCompras = new SetorCompras(this.funcionario);
            setorCompras.setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null,"Somente Diretor pode acessar essa area");
        }
        
    }//GEN-LAST:event_jBCompraActionPerformed

    private void jBDiretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDiretorActionPerformed
        try{
        if (funcionario.getTipo().equals("DIRETOR")){
            TelaDiretor telaDiretor = new TelaDiretor(this.funcionario);
            telaDiretor.setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null,"Somente Diretor pode acessar essa area");
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erro: "+e.getMessage());
        }
    }//GEN-LAST:event_jBDiretorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtualizar;
    private javax.swing.JButton jBCompra;
    private javax.swing.JButton jBConsulta;
    private javax.swing.JButton jBDiretor;
    private javax.swing.JButton jBLocacao;
    private javax.swing.JButton jBRecepcao;
    private javax.swing.JButton jBVenda;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
