package PacotePrincipal;
// Generated 03/04/2013 16:45:21 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Aluguel generated by hbm2java
 */
public class Aluguel  implements java.io.Serializable {


     private int codaluguel;
     private Veiculo veiculo;
     private Cliente cliente;
     private Funcionario funcionario;
     private Date dataaluguel;
     private String tipoaluguel;
     private Date datapagamento;
     private Date datadevolucao;
     private String formapagamento;
     private Set taxaaluguels = new HashSet(0);

    public Aluguel() {
    }

	
    public Aluguel(int codaluguel, Veiculo veiculo, Cliente cliente, Funcionario funcionario, Date dataaluguel, String tipoaluguel) {
        this.codaluguel = codaluguel;
        this.veiculo = veiculo;
        this.cliente = cliente;
        this.funcionario = funcionario;
        this.dataaluguel = dataaluguel;
        this.tipoaluguel = tipoaluguel;
    }
    public Aluguel(int codaluguel, Veiculo veiculo, Cliente cliente, Funcionario funcionario, Date dataaluguel, String tipoaluguel, Date datapagamento, Date datadevolucao, String formapagamento, Set taxaaluguels) {
       this.codaluguel = codaluguel;
       this.veiculo = veiculo;
       this.cliente = cliente;
       this.funcionario = funcionario;
       this.dataaluguel = dataaluguel;
       this.tipoaluguel = tipoaluguel;
       this.datapagamento = datapagamento;
       this.datadevolucao = datadevolucao;
       this.formapagamento = formapagamento;
       this.taxaaluguels = taxaaluguels;
    }
   
    public int getCodaluguel() {
        return this.codaluguel;
    }
    
    public void setCodaluguel(int codaluguel) {
        this.codaluguel = codaluguel;
    }
    public Veiculo getVeiculo() {
        return this.veiculo;
    }
    
    public void setVeiculo(Veiculo veiculo) {
        this.veiculo = veiculo;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Date getDataaluguel() {
        return this.dataaluguel;
    }
    
    public void setDataaluguel(Date dataaluguel) {
        this.dataaluguel = dataaluguel;
    }
    public String getTipoaluguel() {
        return this.tipoaluguel;
    }
    
    public void setTipoaluguel(String tipoaluguel) {
        this.tipoaluguel = tipoaluguel;
    }
    public Date getDatapagamento() {
        return this.datapagamento;
    }
    
    public void setDatapagamento(Date datapagamento) {
        this.datapagamento = datapagamento;
    }
    public Date getDatadevolucao() {
        return this.datadevolucao;
    }
    
    public void setDatadevolucao(Date datadevolucao) {
        this.datadevolucao = datadevolucao;
    }
    public String getFormapagamento() {
        return this.formapagamento;
    }
    
    public void setFormapagamento(String formapagamento) {
        this.formapagamento = formapagamento;
    }
    public Set getTaxaaluguels() {
        return this.taxaaluguels;
    }
    
    public void setTaxaaluguels(Set taxaaluguels) {
        this.taxaaluguels = taxaaluguels;
    }




}


