package PacotePrincipal;
// Generated 03/04/2013 16:45:21 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int codcliente;
     private Cliente cliente;
     private Endereco endereco;
     private String nome;
     private Date datanascimento;
     private String email;
     private int numendereco;
     private String cpf;
     private String numcnh;
     private String tipocnh;
     private Date dataemissaocnh;
     private Date datavalidadecnh;
     private String cnpj;
     private String telefone;
     private Set aluguels = new HashSet(0);
     private Set vendas = new HashSet(0);
     private Set clientes = new HashSet(0);

    public Cliente() {
    }
	
    public Cliente(int codcliente, Endereco endereco, String nome, Date datanascimento, int numendereco, String numcnh, Date dataemissaocnh, Date datavalidadecnh, String telefone) {
        this.codcliente = codcliente;
        this.endereco = endereco;
        this.nome = nome;
        this.datanascimento = datanascimento;
        this.numendereco = numendereco;
        this.numcnh = numcnh;
        this.dataemissaocnh = dataemissaocnh;
        this.datavalidadecnh = datavalidadecnh;
        this.telefone = telefone;
    }
    public Cliente(int codcliente, Cliente cliente, Endereco endereco, String nome, Date datanascimento, String email, int numendereco, String cpf, String numcnh, String tipocnh, Date dataemissaocnh, Date datavalidadecnh, String cnpj, String telefone, Set aluguels, Set vendas, Set clientes) {
       this.codcliente = codcliente;
       this.cliente = cliente;
       this.endereco = endereco;
       this.nome = nome;
       this.datanascimento = datanascimento;
       this.email = email;
       this.numendereco = numendereco;
       this.cpf = cpf;
       this.numcnh = numcnh;
       this.tipocnh = tipocnh;
       this.dataemissaocnh = dataemissaocnh;
       this.datavalidadecnh = datavalidadecnh;
       this.cnpj = cnpj;
       this.telefone = telefone;
       this.aluguels = aluguels;
       this.vendas = vendas;
       this.clientes = clientes;
    }
   
    public int getCodcliente() {
        return this.codcliente;
    }
    
    public void setCodcliente(int codcliente) {
        this.codcliente = codcliente;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Date getDatanascimento() {
        return this.datanascimento;
    }
    
    public void setDatanascimento(Date datanascimento) {
        this.datanascimento = datanascimento;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getNumendereco() {
        return this.numendereco;
    }
    
    public void setNumendereco(int numendereco) {
        this.numendereco = numendereco;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getNumcnh() {
        return this.numcnh;
    }
    
    public void setNumcnh(String numcnh) {
        this.numcnh = numcnh;
    }
    public String getTipocnh() {
        return this.tipocnh;
    }
    
    public void setTipocnh(String tipocnh) {
        this.tipocnh = tipocnh;
    }
    public Date getDataemissaocnh() {
        return this.dataemissaocnh;
    }
    
    public void setDataemissaocnh(Date dataemissaocnh) {
        this.dataemissaocnh = dataemissaocnh;
    }
    public Date getDatavalidadecnh() {
        return this.datavalidadecnh;
    }
    
    public void setDatavalidadecnh(Date datavalidadecnh) {
        this.datavalidadecnh = datavalidadecnh;
    }
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public Set getAluguels() {
        return this.aluguels;
    }
    
    public void setAluguels(Set aluguels) {
        this.aluguels = aluguels;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


