package PacotePrincipal;
// Generated 03/04/2013 16:45:21 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private int codcompra;
     private Funcionario funcionario;
     private Fornecedor fornecedor;
     private Date datacompra;
     private Set veiculos = new HashSet(0);

    public Compra() {
    }

	
    public Compra(int codcompra, Funcionario funcionario, Fornecedor fornecedor, Date datacompra) {
        this.codcompra = codcompra;
        this.funcionario = funcionario;
        this.fornecedor = fornecedor;
        this.datacompra = datacompra;
    }
    public Compra(int codcompra, Funcionario funcionario, Fornecedor fornecedor, Date datacompra, Set veiculos) {
       this.codcompra = codcompra;
       this.funcionario = funcionario;
       this.fornecedor = fornecedor;
       this.datacompra = datacompra;
       this.veiculos = veiculos;
    }
   
    public int getCodcompra() {
        return this.codcompra;
    }
    
    public void setCodcompra(int codcompra) {
        this.codcompra = codcompra;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }
    public Date getDatacompra() {
        return this.datacompra;
    }
    
    public void setDatacompra(Date datacompra) {
        this.datacompra = datacompra;
    }
    public Set getVeiculos() {
        return this.veiculos;
    }
    
    public void setVeiculos(Set veiculos) {
        this.veiculos = veiculos;
    }




}


