package PacotePrincipal;
// Generated 03/04/2013 16:45:21 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Endereco generated by hbm2java
 */
public class Endereco  implements java.io.Serializable {


     private int codendereco;
     private String uf;
     private String bairro;
     private String rua;
     private String cep;
     private String complemento;
     private String cidade;
     private Set fornecedors = new HashSet(0);
     private Set funcionarios = new HashSet(0);
     private Set clientes = new HashSet(0);

    public Endereco() {
    }

    public Endereco(int codendereco, String uf, String bairro, String rua, String cep, String cidade) {
        this.codendereco = codendereco;
        this.uf = uf;
        this.bairro = bairro;
        this.rua = rua;
        this.cep = cep;
        this.cidade = cidade;
    }
    public Endereco(int codendereco, String uf, String bairro, String rua, String cep, String complemento, String cidade, Set fornecedors, Set funcionarios, Set clientes) {
       this.codendereco = codendereco;
       this.uf = uf;
       this.bairro = bairro;
       this.rua = rua;
       this.cep = cep;
       this.complemento = complemento;
       this.cidade = cidade;
       this.fornecedors = fornecedors;
       this.funcionarios = funcionarios;
       this.clientes = clientes;
    }
   
    public int getCodendereco() {
        return this.codendereco;
    }
    
    public void setCodendereco(int codendereco) {
        this.codendereco = codendereco;
    }
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getRua() {
        return this.rua;
    }
    
    public void setRua(String rua) {
        this.rua = rua;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public Set getFornecedors() {
        return this.fornecedors;
    }
    
    public void setFornecedors(Set fornecedors) {
        this.fornecedors = fornecedors;
    }
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


