package PacotePrincipal;
// Generated 03/04/2013 16:45:21 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private int codfuncionario;
     private Setor setor;
     private Endereco endereco;
     private Date datanascimento;
     private String cpf;
     private String nome;
     private String senha;
     private String login;
     private int numendereco;
     private String tipo;
     private String telefone;
     private Set manutencaos = new HashSet(0);
     private Set aluguels = new HashSet(0);
     private Set vendas = new HashSet(0);
     private Set compras = new HashSet(0);

    public Funcionario() {
    }

	
    public Funcionario(int codfuncionario, Setor setor, Endereco endereco, Date datanascimento, String nome, String senha, String login, int numendereco, String tipo, String telefone) {
        this.codfuncionario = codfuncionario;
        this.setor = setor;
        this.endereco = endereco;
        this.datanascimento = datanascimento;
        this.nome = nome;
        this.senha = senha;
        this.login = login;
        this.numendereco = numendereco;
        this.tipo = tipo;
        this.telefone = telefone;
    }
    public Funcionario(int codfuncionario, Setor setor, Endereco endereco, Date datanascimento, String cpf, String nome, String senha, String login, int numendereco, String tipo, String telefone, Set manutencaos, Set aluguels, Set vendas, Set compras) {
       this.codfuncionario = codfuncionario;
       this.setor = setor;
       this.endereco = endereco;
       this.datanascimento = datanascimento;
       this.cpf = cpf;
       this.nome = nome;
       this.senha = senha;
       this.login = login;
       this.numendereco = numendereco;
       this.tipo = tipo;
       this.telefone = telefone;
       this.manutencaos = manutencaos;
       this.aluguels = aluguels;
       this.vendas = vendas;
       this.compras = compras;
    }
   
    public int getCodfuncionario() {
        return this.codfuncionario;
    }
    
    public void setCodfuncionario(int codfuncionario) {
        this.codfuncionario = codfuncionario;
    }
    public Setor getSetor() {
        return this.setor;
    }
    
    public void setSetor(Setor setor) {
        this.setor = setor;
    }
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
    public Date getDatanascimento() {
        return this.datanascimento;
    }
    
    public void setDatanascimento(Date datanascimento) {
        this.datanascimento = datanascimento;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public int getNumendereco() {
        return this.numendereco;
    }
    
    public void setNumendereco(int numendereco) {
        this.numendereco = numendereco;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public Set getManutencaos() {
        return this.manutencaos;
    }
    
    public void setManutencaos(Set manutencaos) {
        this.manutencaos = manutencaos;
    }
    public Set getAluguels() {
        return this.aluguels;
    }
    
    public void setAluguels(Set aluguels) {
        this.aluguels = aluguels;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }




}


