package PacotePrincipal;
// Generated 03/04/2013 16:45:21 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Manutencao generated by hbm2java
 */
public class Manutencao  implements java.io.Serializable {


     private int codmanutencao;
     private Veiculo veiculo;
     private Funcionario funcionario;
     private BigDecimal preco;
     private Date datamanutencao;
     private String descricao;

    public Manutencao() {
    }

    public Manutencao(int codmanutencao, Veiculo veiculo, Funcionario funcionario, BigDecimal preco, Date datamanutencao, String descricao) {
       this.codmanutencao = codmanutencao;
       this.veiculo = veiculo;
       this.funcionario = funcionario;
       this.preco = preco;
       this.datamanutencao = datamanutencao;
       this.descricao = descricao;
    }
   
    public int getCodmanutencao() {
        return this.codmanutencao;
    }
    
    public void setCodmanutencao(int codmanutencao) {
        this.codmanutencao = codmanutencao;
    }
    public Veiculo getVeiculo() {
        return this.veiculo;
    }
    
    public void setVeiculo(Veiculo veiculo) {
        this.veiculo = veiculo;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public BigDecimal getPreco() {
        return this.preco;
    }
    
    public void setPreco(BigDecimal preco) {
        this.preco = preco;
    }
    public Date getDatamanutencao() {
        return this.datamanutencao;
    }
    
    public void setDatamanutencao(Date datamanutencao) {
        this.datamanutencao = datamanutencao;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


