package PacotePrincipal;
// Generated 03/04/2013 16:45:21 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Promocao generated by hbm2java
 */
public class Promocao  implements java.io.Serializable {


     private int codpromocao;
     private Date datafimpromocao;
     private String descricao;
     private Date datainiciopromocao;
     private BigDecimal percentualdesconto;
     private int tipopromocao;
     private Set promocaoveiculos = new HashSet(0);

    public Promocao() {
    }

	
    public Promocao(int codpromocao, Date datafimpromocao, Date datainiciopromocao, BigDecimal percentualdesconto, int tipopromocao) {
        this.codpromocao = codpromocao;
        this.datafimpromocao = datafimpromocao;
        this.datainiciopromocao = datainiciopromocao;
        this.percentualdesconto = percentualdesconto;
        this.tipopromocao = tipopromocao;
    }
    public Promocao(int codpromocao, Date datafimpromocao, String descricao, Date datainiciopromocao, BigDecimal percentualdesconto, int tipopromocao, Set promocaoveiculos) {
       this.codpromocao = codpromocao;
       this.datafimpromocao = datafimpromocao;
       this.descricao = descricao;
       this.datainiciopromocao = datainiciopromocao;
       this.percentualdesconto = percentualdesconto;
       this.tipopromocao = tipopromocao;
       this.promocaoveiculos = promocaoveiculos;
    }
   
    public int getCodpromocao() {
        return this.codpromocao;
    }
    
    public void setCodpromocao(int codpromocao) {
        this.codpromocao = codpromocao;
    }
    public Date getDatafimpromocao() {
        return this.datafimpromocao;
    }
    
    public void setDatafimpromocao(Date datafimpromocao) {
        this.datafimpromocao = datafimpromocao;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Date getDatainiciopromocao() {
        return this.datainiciopromocao;
    }
    
    public void setDatainiciopromocao(Date datainiciopromocao) {
        this.datainiciopromocao = datainiciopromocao;
    }
    public BigDecimal getPercentualdesconto() {
        return this.percentualdesconto;
    }
    
    public void setPercentualdesconto(BigDecimal percentualdesconto) {
        this.percentualdesconto = percentualdesconto;
    }
    public int getTipopromocao() {
        return this.tipopromocao;
    }
    
    public void setTipopromocao(int tipopromocao) {
        this.tipopromocao = tipopromocao;
    }
    public Set getPromocaoveiculos() {
        return this.promocaoveiculos;
    }
    
    public void setPromocaoveiculos(Set promocaoveiculos) {
        this.promocaoveiculos = promocaoveiculos;
    }

}


