package PacotePrincipal;
// Generated 03/04/2013 16:45:21 by Hibernate Tools 3.2.1.GA
/**
 * Promocaoveiculo generated by hbm2java
 */
public class Promocaoveiculo  implements java.io.Serializable {

     private PromocaoveiculoId id;
     private Veiculo veiculo;
     private Promocao promocao;
     private Integer mapear;

    public Promocaoveiculo() {
    }
	
    public Promocaoveiculo(PromocaoveiculoId id, Veiculo veiculo, Promocao promocao) {
        this.id = id;
        this.veiculo = veiculo;
        this.promocao = promocao;
    }
    public Promocaoveiculo(PromocaoveiculoId id, Veiculo veiculo, Promocao promocao, Integer mapear) {
       this.id = id;
       this.veiculo = veiculo;
       this.promocao = promocao;
       this.mapear = mapear;
    }
   
    public PromocaoveiculoId getId() {
        return this.id;
    }
    
    public void setId(PromocaoveiculoId id) {
        this.id = id;
    }
    public Veiculo getVeiculo() {
        return this.veiculo;
    }
    
    public void setVeiculo(Veiculo veiculo) {
        this.veiculo = veiculo;
    }
    public Promocao getPromocao() {
        return this.promocao;
    }
    
    public void setPromocao(Promocao promocao) {
        this.promocao = promocao;
    }
    public Integer getMapear() {
        return this.mapear;
    }
    
    public void setMapear(Integer mapear) {
        this.mapear = mapear;
    }

}


