package PacotePrincipal;
// Generated 03/04/2013 16:45:21 by Hibernate Tools 3.2.1.GA



/**
 * PromocaoveiculoId generated by hbm2java
 */
public class PromocaoveiculoId  implements java.io.Serializable {


     private int codpromocao;
     private int codveiculo;

    public PromocaoveiculoId() {
    }

    public PromocaoveiculoId(int codpromocao, int codveiculo) {
       this.codpromocao = codpromocao;
       this.codveiculo = codveiculo;
    }
   
    public int getCodpromocao() {
        return this.codpromocao;
    }
    
    public void setCodpromocao(int codpromocao) {
        this.codpromocao = codpromocao;
    }
    public int getCodveiculo() {
        return this.codveiculo;
    }
    
    public void setCodveiculo(int codveiculo) {
        this.codveiculo = codveiculo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PromocaoveiculoId) ) return false;
		 PromocaoveiculoId castOther = ( PromocaoveiculoId ) other; 
         
		 return (this.getCodpromocao()==castOther.getCodpromocao())
 && (this.getCodveiculo()==castOther.getCodveiculo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodpromocao();
         result = 37 * result + this.getCodveiculo();
         return result;
   }   


}


