package PacotePrincipal;
// Generated 03/04/2013 16:45:21 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Setor generated by hbm2java
 */
public class Setor  implements java.io.Serializable {


     private int codsetor;
     private String setor;
     private Set funcionarios = new HashSet(0);

    public Setor() {
    }

	
    public Setor(int codsetor, String setor) {
        this.codsetor = codsetor;
        this.setor = setor;
    }
    public Setor(int codsetor, String setor, Set funcionarios) {
       this.codsetor = codsetor;
       this.setor = setor;
       this.funcionarios = funcionarios;
    }
   
    public int getCodsetor() {
        return this.codsetor;
    }
    
    public void setCodsetor(int codsetor) {
        this.codsetor = codsetor;
    }
    public String getSetor() {
        return this.setor;
    }
    
    public void setSetor(String setor) {
        this.setor = setor;
    }
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }




}


