package PacotePrincipal;
// Generated 03/04/2013 16:45:21 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Taxa generated by hbm2java
 */
public class Taxa  implements java.io.Serializable {


     private int codtaxa;
     private Tipoveiculo tipoveiculo;
     private Date datafinaltaxa;
     private Date datainicialtaxa;
     private BigDecimal valortaxa;
     private String tipotaxa;
     private Set taxaaluguels = new HashSet(0);

    public Taxa() {
    }

	
    public Taxa(int codtaxa, Date datafinaltaxa, Date datainicialtaxa, BigDecimal valortaxa, String tipotaxa) {
        this.codtaxa = codtaxa;
        this.datafinaltaxa = datafinaltaxa;
        this.datainicialtaxa = datainicialtaxa;
        this.valortaxa = valortaxa;
        this.tipotaxa = tipotaxa;
    }
    public Taxa(int codtaxa, Tipoveiculo tipoveiculo, Date datafinaltaxa, Date datainicialtaxa, BigDecimal valortaxa, String tipotaxa, Set taxaaluguels) {
       this.codtaxa = codtaxa;
       this.tipoveiculo = tipoveiculo;
       this.datafinaltaxa = datafinaltaxa;
       this.datainicialtaxa = datainicialtaxa;
       this.valortaxa = valortaxa;
       this.tipotaxa = tipotaxa;
       this.taxaaluguels = taxaaluguels;
    }
   
    public int getCodtaxa() {
        return this.codtaxa;
    }
    
    public void setCodtaxa(int codtaxa) {
        this.codtaxa = codtaxa;
    }
    public Tipoveiculo getTipoveiculo() {
        return this.tipoveiculo;
    }
    
    public void setTipoveiculo(Tipoveiculo tipoveiculo) {
        this.tipoveiculo = tipoveiculo;
    }
    public Date getDatafinaltaxa() {
        return this.datafinaltaxa;
    }
    
    public void setDatafinaltaxa(Date datafinaltaxa) {
        this.datafinaltaxa = datafinaltaxa;
    }
    public Date getDatainicialtaxa() {
        return this.datainicialtaxa;
    }
    
    public void setDatainicialtaxa(Date datainicialtaxa) {
        this.datainicialtaxa = datainicialtaxa;
    }
    public BigDecimal getValortaxa() {
        return this.valortaxa;
    }
    
    public void setValortaxa(BigDecimal valortaxa) {
        this.valortaxa = valortaxa;
    }
    public String getTipotaxa() {
        return this.tipotaxa;
    }
    
    public void setTipotaxa(String tipotaxa) {
        this.tipotaxa = tipotaxa;
    }
    public Set getTaxaaluguels() {
        return this.taxaaluguels;
    }
    
    public void setTaxaaluguels(Set taxaaluguels) {
        this.taxaaluguels = taxaaluguels;
    }




}


