package PacotePrincipal;
// Generated 03/04/2013 16:45:21 by Hibernate Tools 3.2.1.GA



/**
 * Taxaaluguel generated by hbm2java
 */
public class Taxaaluguel  implements java.io.Serializable {


     private TaxaaluguelId id;
     private Taxa taxa;
     private Aluguel aluguel;
     private Integer mapear;

    public Taxaaluguel() {
    }

	
    public Taxaaluguel(TaxaaluguelId id, Taxa taxa, Aluguel aluguel) {
        this.id = id;
        this.taxa = taxa;
        this.aluguel = aluguel;
    }
    public Taxaaluguel(TaxaaluguelId id, Taxa taxa, Aluguel aluguel, Integer mapear) {
       this.id = id;
       this.taxa = taxa;
       this.aluguel = aluguel;
       this.mapear = mapear;
    }
   
    public TaxaaluguelId getId() {
        return this.id;
    }
    
    public void setId(TaxaaluguelId id) {
        this.id = id;
    }
    public Taxa getTaxa() {
        return this.taxa;
    }
    
    public void setTaxa(Taxa taxa) {
        this.taxa = taxa;
    }
    public Aluguel getAluguel() {
        return this.aluguel;
    }
    
    public void setAluguel(Aluguel aluguel) {
        this.aluguel = aluguel;
    }
    public Integer getMapear() {
        return this.mapear;
    }
    
    public void setMapear(Integer mapear) {
        this.mapear = mapear;
    }




}


