package PacotePrincipal;
// Generated 03/04/2013 16:45:21 by Hibernate Tools 3.2.1.GA



/**
 * TaxaaluguelId generated by hbm2java
 */
public class TaxaaluguelId  implements java.io.Serializable {


     private int codtaxa;
     private int codaluguel;

    public TaxaaluguelId() {
    }

    public TaxaaluguelId(int codtaxa, int codaluguel) {
       this.codtaxa = codtaxa;
       this.codaluguel = codaluguel;
    }
   
    public int getCodtaxa() {
        return this.codtaxa;
    }
    
    public void setCodtaxa(int codtaxa) {
        this.codtaxa = codtaxa;
    }
    public int getCodaluguel() {
        return this.codaluguel;
    }
    
    public void setCodaluguel(int codaluguel) {
        this.codaluguel = codaluguel;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaxaaluguelId) ) return false;
		 TaxaaluguelId castOther = ( TaxaaluguelId ) other; 
         
		 return (this.getCodtaxa()==castOther.getCodtaxa())
 && (this.getCodaluguel()==castOther.getCodaluguel());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodtaxa();
         result = 37 * result + this.getCodaluguel();
         return result;
   }   


}


