package PacotePrincipal;
// Generated 03/04/2013 16:45:21 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoveiculo generated by hbm2java
 */
public class Tipoveiculo  implements java.io.Serializable {


     private int codtipoveiculo;
     private String tipo;
     private Set veiculos = new HashSet(0);
     private Set taxas = new HashSet(0);

    public Tipoveiculo() {
    }

	
    public Tipoveiculo(int codtipoveiculo, String tipo) {
        this.codtipoveiculo = codtipoveiculo;
        this.tipo = tipo;
    }
    public Tipoveiculo(int codtipoveiculo, String tipo, Set veiculos, Set taxas) {
       this.codtipoveiculo = codtipoveiculo;
       this.tipo = tipo;
       this.veiculos = veiculos;
       this.taxas = taxas;
    }
   
    public int getCodtipoveiculo() {
        return this.codtipoveiculo;
    }
    
    public void setCodtipoveiculo(int codtipoveiculo) {
        this.codtipoveiculo = codtipoveiculo;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getVeiculos() {
        return this.veiculos;
    }
    
    public void setVeiculos(Set veiculos) {
        this.veiculos = veiculos;
    }
    public Set getTaxas() {
        return this.taxas;
    }
    
    public void setTaxas(Set taxas) {
        this.taxas = taxas;
    }




}


