package PacotePrincipal;
// Generated 03/04/2013 16:45:21 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Veiculo generated by hbm2java
 */
public class Veiculo  implements java.io.Serializable {


     private int codveiculo;
     private Tipoveiculo tipoveiculo;
     private Compra compra;
     private Venda venda;
     private String combustivel;
     private String modelo;
     private BigDecimal kilometragem;
     private String chassi;
     private String status;
     private String cor;
     private Integer ano;
     private String placa;
     private Set manutencaos = new HashSet(0);
     private Set promocaoveiculos = new HashSet(0);
     private Set aluguels = new HashSet(0);

    public Veiculo() {
    }

	
    public Veiculo(int codveiculo, Tipoveiculo tipoveiculo, Compra compra, BigDecimal kilometragem, String status, String placa) {
        this.codveiculo = codveiculo;
        this.tipoveiculo = tipoveiculo;
        this.compra = compra;
        this.kilometragem = kilometragem;
        this.status = status;
        this.placa = placa;
    }
    public Veiculo(int codveiculo, Tipoveiculo tipoveiculo, Compra compra, Venda venda, String combustivel, String modelo, BigDecimal kilometragem, String chassi, String status, String cor, Integer ano, String placa, Set manutencaos, Set promocaoveiculos, Set aluguels) {
       this.codveiculo = codveiculo;
       this.tipoveiculo = tipoveiculo;
       this.compra = compra;
       this.venda = venda;
       this.combustivel = combustivel;
       this.modelo = modelo;
       this.kilometragem = kilometragem;
       this.chassi = chassi;
       this.status = status;
       this.cor = cor;
       this.ano = ano;
       this.placa = placa;
       this.manutencaos = manutencaos;
       this.promocaoveiculos = promocaoveiculos;
       this.aluguels = aluguels;
    }
   
    public int getCodveiculo() {
        return this.codveiculo;
    }
    
    public void setCodveiculo(int codveiculo) {
        this.codveiculo = codveiculo;
    }
    public Tipoveiculo getTipoveiculo() {
        return this.tipoveiculo;
    }
    
    public void setTipoveiculo(Tipoveiculo tipoveiculo) {
        this.tipoveiculo = tipoveiculo;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Venda getVenda() {
        return this.venda;
    }
    
    public void setVenda(Venda venda) {
        this.venda = venda;
    }
    public String getCombustivel() {
        return this.combustivel;
    }
    
    public void setCombustivel(String combustivel) {
        this.combustivel = combustivel;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public BigDecimal getKilometragem() {
        return this.kilometragem;
    }
    
    public void setKilometragem(BigDecimal kilometragem) {
        this.kilometragem = kilometragem;
    }
    public String getChassi() {
        return this.chassi;
    }
    
    public void setChassi(String chassi) {
        this.chassi = chassi;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getCor() {
        return this.cor;
    }
    
    public void setCor(String cor) {
        this.cor = cor;
    }
    public Integer getAno() {
        return this.ano;
    }
    
    public void setAno(Integer ano) {
        this.ano = ano;
    }
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }
    public Set getManutencaos() {
        return this.manutencaos;
    }
    
    public void setManutencaos(Set manutencaos) {
        this.manutencaos = manutencaos;
    }
    public Set getPromocaoveiculos() {
        return this.promocaoveiculos;
    }
    
    public void setPromocaoveiculos(Set promocaoveiculos) {
        this.promocaoveiculos = promocaoveiculos;
    }
    public Set getAluguels() {
        return this.aluguels;
    }
    
    public void setAluguels(Set aluguels) {
        this.aluguels = aluguels;
    }




}


