package PacotePrincipal;
// Generated 03/04/2013 16:45:21 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venda generated by hbm2java
 */
public class Venda  implements java.io.Serializable {


     private int codvenda;
     private Cliente cliente;
     private Funcionario funcionario;
     private Date datavenda;
     private Set veiculos = new HashSet(0);

    public Venda() {
    }

	
    public Venda(int codvenda, Cliente cliente, Funcionario funcionario, Date datavenda) {
        this.codvenda = codvenda;
        this.cliente = cliente;
        this.funcionario = funcionario;
        this.datavenda = datavenda;
    }
    public Venda(int codvenda, Cliente cliente, Funcionario funcionario, Date datavenda, Set veiculos) {
       this.codvenda = codvenda;
       this.cliente = cliente;
       this.funcionario = funcionario;
       this.datavenda = datavenda;
       this.veiculos = veiculos;
    }
   
    public int getCodvenda() {
        return this.codvenda;
    }
    
    public void setCodvenda(int codvenda) {
        this.codvenda = codvenda;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Date getDatavenda() {
        return this.datavenda;
    }
    
    public void setDatavenda(Date datavenda) {
        this.datavenda = datavenda;
    }
    public Set getVeiculos() {
        return this.veiculos;
    }
    
    public void setVeiculos(Set veiculos) {
        this.veiculos = veiculos;
    }




}


